import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';import {readFile} from 'node:fs/promises';import {crearHandlerEstudiante} from '../api/estudiante.js';
const db=new PGlite();await db.exec(`create schema auth;create role anon;create role authenticated;create role service_role;create type rol_usuario as enum('estudiante','profesor','acudiente');create table auth.users(id uuid primary key,email text);create table perfiles(id uuid primary key,nombre text,rol rol_usuario);create table estudiantes(id uuid primary key,nombre text,email text,documento text,activo boolean,auth_user_id uuid);create table invitaciones_profesor(email text);create table acudientes(auth_user_id uuid);`);
const sql=await readFile(new URL('../supabase/acceso-estudiantes-documento.sql',import.meta.url),'utf8');await db.exec(sql);await db.exec(sql);
const student='10000000-0000-0000-0000-000000000001',user='20000000-0000-0000-0000-000000000001';await db.query('insert into estudiantes values($1,$2,$3,$4,true,null)',[student,'Ejemplo','uno@example.edu','001234567']);
const prepare=async(email='uno@example.edu',doc='001234567')=>(await db.query('select preparar_acceso_estudiante($1,$2) data',[email,doc])).rows[0].data;
assert.equal(await prepare('uno@example.edu','wrong'),null);assert.equal(await prepare('otro@example.edu'),null);assert.deepEqual(await prepare(),{email:'uno@example.edu',crear:true});await db.query('insert into auth.users values($1,$2)',[user,'uno@example.edu']);let result=await prepare();assert.equal(result.id,user);assert.equal((await db.query('select auth_user_id from estudiantes')).rows[0].auth_user_id,user);assert.equal((await db.query('select rol from perfiles')).rows[0].rol,'estudiante');assert.equal((await prepare()).id,user,'Cuenta Google conservada');
await db.exec("update perfiles set rol='profesor'");assert.equal(await prepare(),null);await db.exec("update perfiles set rol='estudiante';insert into acudientes select id from auth.users");assert.equal(await prepare(),null);await db.exec('delete from acudientes');await db.exec("insert into invitaciones_profesor values('uno@example.edu')");assert.equal(await prepare(),null);await db.exec('delete from invitaciones_profesor;update estudiantes set activo=false');assert.equal(await prepare(),null);await db.exec('set role authenticated');await assert.rejects(prepare());await db.exec('reset role');await db.close();
async function api(options={}){let prepared=0;const calls=[];const admin={rpc:async(name)=>{calls.push(name);if(options.missing)return{error:{}};if(name==='acudiente_registrar_intento')return{data:!options.limited};prepared++;return{data:options.denied?null:{email:'uno@example.edu',crear:options.new&&prepared===1,id:options.new&&prepared===1?undefined:user}}},auth:{admin:{createUser:async args=>{calls.push('create');assert.equal(args.password,'001234567');return{}},updateUserById:async(id,args)=>{calls.push('update');assert.equal(id,user);assert.equal(args.password,'001234567');return{}}}}};const auth={auth:{signInWithPassword:async()=>{calls.push('signin');return{data:{session:{access_token:'a',refresh_token:'r'}}}}}};const h=crearHandlerEstudiante((url,key)=>key==='secret'?admin:auth,{SUPABASE_URL:'url',SUPABASE_SERVICE_ROLE_KEY:'secret',SUPABASE_ANON_KEY:'anon'});const res={setHeader(){},status(c){this.code=c;return this},json(d){this.data=d;return this}};await h({method:'POST',body:{email:'uno@example.edu',password:'001234567'}},res);return{...res,calls}}
for(const options of [{},{new:true}]){const r=await api(options);assert.equal(r.code,200);assert.deepEqual(r.data,{access_token:'a',refresh_token:'r'});assert(r.calls.indexOf('update')<r.calls.indexOf('signin'))}assert.equal((await api({denied:true})).code,401);assert.equal((await api({limited:true})).code,429);assert.equal((await api({missing:true})).code,503);assert(!(await api({denied:true})).calls.includes('update'));
console.log('PASS: SQL repetible; correo/documento exactos; cuentas nuevas y Google; vínculos conservados; profesores/acudientes/inactivos protegidos; RPC exclusiva servidor; API y límites');
