import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
const teacher='00000000-0000-0000-0000-000000000001',child='00000000-0000-0000-0000-000000000002',parent='00000000-0000-0000-0000-000000000003',child2='00000000-0000-0000-0000-000000000004',parent2='00000000-0000-0000-0000-000000000005';
const student='10000000-0000-0000-0000-000000000001',other='10000000-0000-0000-0000-000000000002',record='20000000-0000-0000-0000-000000000001',record2='20000000-0000-0000-0000-000000000002';
await db.exec(`create schema auth;create schema storage;create role anon;create role authenticated;create role service_role;grant usage on schema public,auth,storage to authenticated,service_role;
create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
create type rol_usuario as enum('profesor','estudiante');create table perfiles(id uuid primary key,nombre text,rol rol_usuario);
create function es_profesor() returns boolean language sql stable security definer as $$select exists(select 1 from public.perfiles where id=auth.uid() and rol='profesor')$$;
create table estudiantes(id uuid primary key,nombre text,grado integer,email text,documento text,auth_user_id uuid,activo boolean default true);
create table asignaciones(estudiante_id uuid,dia integer);create table registros_aseo(id uuid primary key,fecha date,observaciones text);
create table participaciones(id uuid primary key,estudiante_id uuid,registro_id uuid,estado text,calificacion integer);
create table tareas(participacion_id uuid,tipo text,detalle text,realizada boolean);create table evidencias(id uuid,registro_id uuid,reporte_id uuid,path text,subido_por uuid);
create table valoraciones(autor uuid,valor integer);create table reportes(id uuid,autor uuid,tipo text,descripcion text,estado text,created_at timestamptz default now());
create table avisos(id uuid,tipo text,titulo text,contenido text,grado integer,fecha_evento date,publicado boolean,created_at timestamptz default now());
create table mensajes_estudiantes(id uuid,titulo text,contenido text,estado text,created_at timestamptz default now());
create table horario_base(grupo text,dia integer,bloque integer,materia text,profesor text);create table horario_cambios(grupo text,fecha date,bloque integer,materia text,profesor text,cancelada boolean,aviso text);
create table storage.objects(bucket_id text,name text);alter table storage.objects enable row level security;
create policy old_read on storage.objects for select to authenticated using(false);create policy old_insert on storage.objects for insert to authenticated with check(true);
grant select,insert,update,delete on all tables in schema public,storage to authenticated;
insert into auth.users values('${teacher}'),('${child}'),('${parent}'),('${child2}'),('${parent2}');
insert into perfiles values('${teacher}','Profesor','profesor'),('${child}','Hijo uno','estudiante'),('${parent}','Provisional','estudiante'),('${child2}','Hijo dos','estudiante');
insert into estudiantes values('${student}','Hijo uno',6,'uno@example.edu','00123456','${child}',true),('${other}','Hijo dos',7,'dos@example.edu','N999999','${child2}',true);
insert into asignaciones values('${student}',1),('${other}',2);insert into registros_aseo values('${record}','2026-10-01','Registro propio'),('${record2}','2026-10-02','Registro ajeno');
insert into participaciones values('30000000-0000-0000-0000-000000000001','${student}','${record}','cumplio',9),('30000000-0000-0000-0000-000000000002','${other}','${record2}','cumplio',4);
insert into tareas values('30000000-0000-0000-0000-000000000001','barrer',null,true);
insert into evidencias values('40000000-0000-0000-0000-000000000001','${record}',null,'propia.jpg','${teacher}'),('40000000-0000-0000-0000-000000000002','${record2}',null,'ajena.jpg','${teacher}'),('40000000-0000-0000-0000-000000000003','${record}',null,'compañero.jpg','${child2}');
insert into storage.objects values('evidencias','propia.jpg'),('evidencias','ajena.jpg'),('evidencias','compañero.jpg');
insert into reportes(id,autor,tipo,descripcion,estado) values(gen_random_uuid(),'${child}','convivencia','Propio','pendiente'),(gen_random_uuid(),'${child2}','aseo','Ajeno','revisado');
insert into avisos(id,tipo,titulo,contenido,grado,publicado) values(gen_random_uuid(),'evento','Para sexto','Aviso',6,true),(gen_random_uuid(),'evento','Para séptimo','Ajeno',7,true),(gen_random_uuid(),'evento','Oculto','Oculto',6,false);
insert into horario_base values('6',1,1,'Matemáticas','Gustavo'),('7-8',1,1,'Inglés','Gustavo');
`);
for(const table of ['perfiles','estudiantes','asignaciones','registros_aseo','participaciones','tareas','evidencias','valoraciones','reportes','avisos','mensajes_estudiantes','horario_base','horario_cambios'])await db.exec(`alter table ${table} enable row level security;create policy old_permissions on ${table} for all to authenticated using(true) with check(true)`);
const sql=await readFile(new URL('../supabase/acudientes.sql',import.meta.url),'utf8');await db.exec(sql);await db.exec(sql);
const rpc=async(name,args=[],casts=[])=>(await db.query(`select ${name}(${args.map((_,i)=>'$'+(i+1)+(casts[i]?'::'+casts[i]:'')).join(',')}) data`,args)).rows[0].data;
assert.equal(await rpc('vincular_cuenta_acudiente',[parent,student],['uuid','uuid']),parent);await rpc('vincular_cuenta_acudiente',[parent2,other],['uuid','uuid']);
assert.equal((await db.query('select auth_user_id from estudiantes where id=$1',[student])).rows[0].auth_user_id,child,'Google del estudiante conservado');
await db.query("select set_config('test.uid',$1,false)",[parent]);await db.exec('set role authenticated');
const data=await rpc('acudiente_contexto');assert.equal(data.estudiante.id,student);assert.equal(data.participaciones.length,1);assert.equal(data.participaciones[0].calificacion,9);assert.equal(data.participaciones[0].evidencias.length,1);assert.equal(data.reportes.length,1);assert.equal(data.avisos.length,1);assert.equal(data.horario_base.length,1);assert.deepEqual(data.turnos,[1]);
assert.equal((await db.query('select * from estudiantes')).rows.length,0);assert.equal((await db.query('select * from participaciones')).rows.length,0);await assert.rejects(db.query(`insert into valoraciones values('${parent}',5)`));await assert.rejects(db.query(`insert into reportes(id,autor,tipo,descripcion,estado)values(gen_random_uuid(),'${parent}','aseo','No','pendiente')`));await assert.rejects(rpc('vincular_cuenta_acudiente',[parent,other],['uuid','uuid']));
assert.deepEqual((await db.query('select name from storage.objects')).rows.map(r=>r.name),['propia.jpg']);await assert.rejects(db.query("insert into storage.objects values('evidencias','subida.jpg')"));
assert.deepEqual(await rpc('acudiente_encuestas'),{encuestas:[],grammy:null});
await db.exec('reset role');await db.query("select set_config('test.uid',$1,false)",[child]);await db.exec('set role authenticated');assert.equal(await rpc('es_acudiente'),false);assert.equal((await db.query('select * from estudiantes')).rows.length,2,'Políticas estudiantiles originales no alteradas');await assert.rejects(rpc('acudiente_contexto'));
await db.exec('reset role');await db.query('update estudiantes set activo=false where id=$1',[student]);await db.query("select set_config('test.uid',$1,false)",[parent]);await assert.rejects(rpc('acudiente_contexto'));assert.equal(await rpc('acudiente_puede_ver_foto',['propia.jpg'],['text']),false);
for(let i=0;i<12;i++)assert.equal(await rpc('acudiente_registrar_intento',['hash'],['text']),true);assert.equal(await rpc('acudiente_registrar_intento',['hash'],['text']),false);
console.log('PASS: SQL repetible; cuenta independiente; hijo propio; notas/fotos/avisos/horario/reportes; restricciones aun con permisos antiguos; Google intacto; inactivos y límites');await db.close();
