import {build} from 'esbuild';import React from 'react';import {create,act} from 'react-test-renderer';import assert from 'node:assert/strict';import {unlink} from 'node:fs/promises';
const root=new URL('..',import.meta.url).pathname.replace(/\/$/,'');const outfile=root+'/node_modules/acudiente-test.mjs';globalThis.IS_REACT_ACT_ENVIRONMENT=true;globalThis.localStorage={getItem(){return null},setItem(){}};globalThis.calls=[];
globalThis.parentData={estudiante:{id:'child',nombre:'Mi estudiante',grado:6,documento:'123456789'},turnos:[1],participaciones:[],avisos:[],mensajes:[],reportes:[],horario_base:[],horario_cambios:[]};
await build({entryPoints:[root+'/src/Acudiente.jsx'],bundle:true,format:'esm',outfile,packages:'external',loader:{'.css':'empty','.png':'dataurl'},plugins:[{name:'parent-fixture',setup(b){b.onLoad({filter:/lib\/supabase.js$/},()=>({contents:`export const supabase={rpc:async(name)=>{globalThis.calls.push(name);return{data:name==='acudiente_contexto'?globalThis.parentData:{encuestas:[],grammy:null}}},auth:{updateUser:async(args)=>{globalThis.calls.push(args);return{}},signOut:async()=>{}}};`}));b.onLoad({filter:/\/(Invitados|AlertaEvacuacion)\.jsx$/},()=>({contents:'export const ConvivenciaEstudiante=()=>null;export default ()=>null;'}))}}]});
const {default:View}=await import(outfile);let view;await act(async()=>{view=create(React.createElement(View,{perfil:{id:'parent'}}))});assert.match(JSON.stringify(view.toJSON()),/Mi estudiante/);
const click=async text=>act(async()=>view.root.findAllByType('button').find(b=>b.children.join('').includes(text)).props.onClick());
for(const tab of ['Horario','Aseo y evidencias','Calificaciones','Avisos','Reportes de mi hijo','Convivencia','Resultados de encuestas']){await click(tab);assert.equal(view.root.findAllByType('form').length,0)}
await click('Mi cuenta');assert.match(JSON.stringify(view.toJSON()),/opcional/);let fields=view.root.findAllByType('input');await act(async()=>{fields[0].props.onChange({target:{value:'newpass'}});fields[1].props.onChange({target:{value:'different'}})});await act(async()=>view.root.findByType('form').props.onSubmit({preventDefault(){}}));assert(!globalThis.calls.some(x=>typeof x==='object'));
await act(async()=>fields[1].props.onChange({target:{value:'newpass'}}));await act(async()=>view.root.findByType('form').props.onSubmit({preventDefault(){}}));assert.deepEqual(globalThis.calls.find(x=>typeof x==='object'),{password:'newpass'});await act(async()=>view.unmount());await unlink(outfile);console.log('PASS: secciones del acudiente solo consulta; cuenta separada; cambio opcional y confirmación de contraseña');
