import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import {interpretarHojas,vincularFilas,documentoValido} from '../src/importarExcel.js';
const original={sheet:'6°',data:[['Nombre del estudiante','Correo','Grado'],['ANA RUIZ','ana@example.edu',6]]};
const nuevo={sheet:'6°',data:[['Nombre del estudiante','Correo','Grado','Documento'],['ANA RUIZ','ana@example.edu',6,'00123456'],['JUAN RÍOS','juan@example.edu',6,'N123456']]};
let filas=interpretarHojas([nuevo]).filas;assert.equal(filas[0].documento,'00123456');assert.equal(filas[1].documento,'N123456');assert.equal(interpretarHojas([original]).filas[0].tieneDocumento,false);assert.equal(documentoValido('N123456'),true);assert.equal(documentoValido('1.2E+9'),false);
const existentes=[{id:'a',nombre:'RUIZ ANA',grado:6,email:'ana@example.edu',documento:null}];
let vinculadas=vincularFilas(filas,existentes,true);assert.equal(vinculadas[0].id,'a');assert.equal(vinculadas[0].omitir,false);assert.equal(vinculadas[1].omitir,true,'Sin ficha se omite para no crear duplicados');
assert.equal(vincularFilas(filas,[{...existentes[0],documento:'00123456'}],true)[0].omitir,true);
assert.match(vincularFilas([{...filas[0],email:'otro@example.edu'}],[...existentes,{...existentes[0],id:'b',email:'b@example.edu'}],true)[0].conflicto,/varias/);
const db=new PGlite();
await db.exec(`create schema auth;create role anon;create role authenticated;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;create function public.es_profesor() returns boolean language sql stable as $$select current_setting('test.profesor',true)='true'$$;create table estudiantes(id uuid primary key default gen_random_uuid(),nombre text,grado integer,email text unique,auth_user_id uuid,activo boolean default true);create table participaciones(estudiante_id uuid references estudiantes(id),nota integer);insert into estudiantes(id,nombre,grado,email,auth_user_id) values('10000000-0000-0000-0000-000000000001','Nombre guardado',6,'ana@example.edu','00000000-0000-0000-0000-000000000002');insert into participaciones values('10000000-0000-0000-0000-000000000001',9);`);
const sql=await readFile(new URL('../supabase/documentos-estudiantes.sql',import.meta.url),'utf8');await db.exec(sql);await db.exec(sql);
await db.query("select set_config('test.uid',$1,false),set_config('test.profesor','true',false)",['00000000-0000-0000-0000-000000000001']);
const id='10000000-0000-0000-0000-000000000001',row={id,nombre:'ANA RUIZ',grado:7,email:'ana@example.edu',documento:'00123456',solo_documento:true};
const importar=async rows=>(await db.query('select importar_estudiantes($1::jsonb) r',[rows])).rows[0].r;
assert.deepEqual(await importar([row]),{creados:0,actualizados:1});
let saved=(await db.query('select * from estudiantes where id=$1',[id])).rows[0];assert.equal(saved.nombre,'Nombre guardado');assert.equal(saved.grado,6);assert.equal(saved.documento,'00123456');assert.equal(saved.auth_user_id,'00000000-0000-0000-0000-000000000002');assert.equal((await db.query('select nota from participaciones')).rows[0].nota,9);
assert.deepEqual(await importar([{...row,id:null,documento:'N123456'}]),{creados:0,actualizados:1},'Coincidencia por correo no duplica');
await importar([{id,nombre:'Nombre guardado',grado:6,email:'ana@example.edu'}]);assert.equal((await db.query('select documento from estudiantes')).rows[0].documento,'N123456','Excel anterior no borra el documento');
await assert.rejects(importar([{...row,id:null,email:'nuevo@example.edu'}]));
await importar([{nombre:'Segundo alumno',grado:5,email:'b@example.edu',documento:'555666'}]);
await assert.rejects(importar([{...row,documento:'555666'}]));
await assert.rejects(importar([{...row,documento:'N123456'}, {...row,id:null,email:'b@example.edu',documento:'N123456'}]));
await assert.rejects(importar([{...row,documento:'999888'},{...row,id:null,email:'nuevo@example.edu',grado:99}]));assert.equal((await db.query('select documento from estudiantes where id=$1',[id])).rows[0].documento,'N123456','Lote inválido no deja actualizaciones parciales');
await db.query("select set_config('test.profesor','false',false)");await assert.rejects(importar([row]));
assert.equal((await db.query('select count(*)::integer total from estudiantes')).rows[0].total,2);
console.log('PASS: documentos como texto; Excel anterior; coincidencias; solo actualizar conserva ficha y aseos; duplicados, permisos y lote atómico');await db.close();
