import {build} from 'esbuild';
import React from 'react';
import {create,act} from 'react-test-renderer';
import assert from 'node:assert/strict';
import {unlink} from 'node:fs/promises';
const root=new URL('..',import.meta.url).pathname.replace(/\/$/,'');
const outfile=root+'/node_modules/encuestas-test-bundle.mjs';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;globalThis.window={confirm:()=>true};
const question={id:'q1',titulo:'¿Quién ayuda más?',descripcion:'',orden:1};
const open={id:'open',titulo:'Encuesta abierta',estado:'abierta',descripcion:'',grados_participantes:[6],grados_candidatos:[7],preguntas:1,mis_respuestas:0};
const closed={...open,id:'closed',titulo:'Encuesta terminada',estado:'cerrada',resultados_publicados:true};
globalThis.surveyList=[open,closed];globalThis.surveyCalls=[];
globalThis.surveyContext=id=>({profesor:true,encuesta:id==='closed'?closed:open,editable:false,puede_responder:id==='open',preguntas:[question],candidatos:id==='open'?[{id:'s1',nombre:'María',grado:7}]:[],mis_respuestas:id==='closed'?{q1:{candidato_id:'s1',nombre:'María',grado:7}}:{},conteo:id==='closed'?[{pregunta_id:'q1',candidato_id:'s1',nombre:'María',grado:7,votos:3}]:null});
await build({entryPoints:[root+'/src/Encuestas.jsx'],bundle:true,format:'esm',outfile,packages:'external',loader:{'.css':'empty'},plugins:[{name:'survey-fixture',setup(b){b.onLoad({filter:/lib\/supabase.js$/},()=>({contents:`export const supabase={rpc:async(name,args)=>{globalThis.surveyCalls.push({name,args});if(name==='encuestas_listar')return{data:globalThis.surveyList};if(name==='encuesta_contexto')return{data:globalThis.surveyContext(args.encuesta)};if(name==='encuesta_guardar')return{data:'open'};return{data:null}}};`}));b.onLoad({filter:/\/Grammy.jsx$/},()=>({contents:'export default ()=>null'}))}}]});
const {default:Encuestas}=await import(outfile);let view;
const buttons=text=>view.root.findAllByType('button').filter(b=>b.children.join('').includes(text));
async function mount(props){await act(async()=>{view=create(React.createElement(Encuestas,props))})}
await mount({grado:6});assert.equal(buttons('Responder encuesta').length,1);assert.equal(buttons('Ver encuesta y mis respuestas').length,1);
await act(async()=>buttons('Responder encuesta')[0].props.onClick());
const select=view.root.findByType('select');assert.deepEqual(select.findAllByType('option').map(o=>o.children.join('')),['Sin respuesta','María · 7°']);
await act(async()=>select.props.onChange({target:{value:'s1'}}));await act(async()=>view.root.findByType('form').props.onSubmit({preventDefault(){}}));
assert.deepEqual(globalThis.surveyCalls.find(c=>c.name==='encuesta_responder').args,{encuesta:'open',elecciones:{q1:'s1'}});
await act(async()=>buttons('Volver a Encuestas')[0].props.onClick());await act(async()=>buttons('Ver encuesta y mis respuestas')[0].props.onClick());assert.equal(view.root.findAllByType('select').length,0);assert.equal(buttons('Guardar mis respuestas').length,0);assert.match(JSON.stringify(view.toJSON()),/María/);assert.match(JSON.stringify(view.toJSON()),/Resultados/);
await act(async()=>view.unmount());await mount({profesor:true});await act(async()=>buttons('Crear encuesta')[0].props.onClick());
await act(async()=>view.root.findAllByType('input').find(i=>!i.props.type).props.onChange({target:{value:'Nueva votación'}}));
const fields=view.root.findAllByType('fieldset');const candidates=fields[1].findAllByType('input');await act(async()=>candidates[5].props.onChange());
await act(async()=>view.root.findByType('form').props.onSubmit({preventDefault(){}}));
const created=globalThis.surveyCalls.find(c=>c.name==='encuesta_guardar');assert.equal(created.args.datos.titulo,'Nueva votación');assert.deepEqual(created.args.datos.grados_participantes,[6,7,8]);assert.deepEqual(created.args.datos.grados_candidatos,[7,8]);
await act(async()=>view.unmount());await unlink(outfile);
console.log('PASS: abiertas y anteriores; candidatos por grado; guarda elecciones; cierre solo lectura; profesor crea con grados distintos');
