import GeneroEstudiante,{referenciaFamiliar as referencia} from './GeneroEstudiante';
import React,{useEffect,useState} from 'react';
import {supabase} from './lib/supabase';
import {fechaBogota,nombresTareas} from './ultimaActividad';
import {notasConRecuperaciones,origenRecuperacion} from './recuperacionesAseo';
import {ConvivenciaEstudiante} from './Invitados';
import AlertaEvacuacion from './AlertaEvacuacion';
import {repartirPremios} from './grammyResultados';
import escudo from './assets/escudo-claudina.png';
import './Acudiente.css';
const dias=['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'];
const estado={cumplio:'✅ Cumplió',ausente:'🚫 Ausente',no_cumplio:'❌ No cumplió'};
const tabs=[['inicio','🏠 Mi hijo'],['horario','🕒 Horario'],['aseo','🧹 Aseo y evidencias'],['avisos','📚 Tareas y Avisos'],['reportes','🚨 Reportes de mi hijo'],['convivencia','🤝 Convivencia'],['encuestas','📋 Resultados de encuestas'],['cuenta','🔐 Mi cuenta']];
export function IngresoAcudiente({onVolver}){
 const[documento,setDocumento]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function entrar(e){e.preventDefault();if(busy)return;setBusy(true);setMsg('');try{
  const respuesta=await fetch('/api/acudiente',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({documento,password})});
  const data=await respuesta.json();if(!respuesta.ok)throw new Error(data.error||'No fue posible ingresar.');
  const{error}=await supabase.auth.setSession({access_token:data.access_token,refresh_token:data.refresh_token});if(error)throw new Error('No se pudo iniciar la sesión. Inténtalo de nuevo.');
 }catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <main className="loginPage"><header><img className="brandShield" src={escudo} alt="Escudo de Claudina Múnera"/><div><h1>Claudina Clean</h1><p>Familias que acompañan</p></div></header><section><div className="loginCard"><h2>👨‍👩‍👧 Acceso de acudiente</h2><p>Consulta la información escolar del estudiante.</p><form onSubmit={entrar}><label>Documento del estudiante<input type="text" autoComplete="username" required maxLength={30} value={documento} onChange={e=>setDocumento(e.target.value.trim().toUpperCase())}/></label><label>Contraseña<input type="password" autoComplete="current-password" required maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label><small>La contraseña inicial es el documento del estudiante. Si ya la cambiaste, usa tu nueva contraseña.</small><button className="save" disabled={busy}>{busy?'Ingresando…':'Ingresar como acudiente'}</button><button type="button" disabled={busy} onClick={onVolver}>← Estudiantes, profesores e invitados</button>{msg&&<p className="error" role="status">{msg}</p>}</form></div></section><footer>C.E.R. Claudina Múnera · Designed by Ghost</footer></main>;
}
function FotosAseo({evidencias,hijo}){
 const[urls,setUrls]=useState([]),[error,setError]=useState('');
 useEffect(()=>{let vigente=true;setUrls([]);setError('');Promise.all(evidencias.map(async f=>{const{data,error}=await supabase.storage.from('evidencias').createSignedUrl(f.path,300);if(error)throw error;return{...f,url:data.signedUrl}})).then(f=>{if(vigente)setUrls(f)}).catch(()=>{if(vigente)setError('No se pudieron abrir las evidencias. Vuelve a intentar más tarde.')});return()=>{vigente=false}},[evidencias]);
 return error?<p className="error">{error}</p>:<div className="evidenceGrid">{urls.map(f=><a key={f.id} href={f.url} target="_blank" rel="noreferrer"><img loading="lazy" src={f.url} alt={`Evidencia del aseo de su ${referencia(hijo)}`}/></a>)}</div>;
}
function AseosAcudiente({filas,hijo}){
 const[abierto,setAbierto]=useState(null);
 return <section><h2>🧹 Aseo y evidencias de mi {referencia(hijo)}</h2><p>Tareas realizadas, observaciones del registro y fotos compartidas por el profesor o por tu {referencia(hijo)}.</p>{!filas.length&&<p className="placeholder">Todavía no hay registros de aseo.</p>}{filas.map(p=><article className="card" key={p.id}><button className="guardianRecord" onClick={()=>setAbierto(abierto===p.id?null:p.id)} aria-expanded={abierto===p.id}><b>{p.fecha}</b><span>{estado[p.estado]||'Sin estado'} · {p.calificacion??'—'}/10{origenRecuperacion(p)?' · Recuperación':''}</span><span>{abierto===p.id?'Cerrar detalle':'Ver tareas y fotos'}</span></button>{abierto===p.id&&<><div className="chips">{p.tareas.filter(t=>t.realizada!==false&&!origenRecuperacion({tareas:[t]})).map((t,i)=><span key={i}>{nombresTareas[t.tipo]||t.tipo}{t.tipo==='aporte_especial'&&t.detalle?`: ${t.detalle}`:''}</span>)}</div>{p.observaciones&&<p><b>Observaciones:</b> {p.observaciones}</p>}{p.evidencias.length?<FotosAseo evidencias={p.evidencias} hijo={hijo}/>:<p>No hay fotos de este aseo disponibles para la familia.</p>}</>}</article>)}</section>;
}
function AvisosAcudiente({avisos,mensajes,hijo}){
 const tareas=avisos.filter(a=>a.tipo==='tarea').sort((a,b)=>a.fecha_evento&&b.fecha_evento?a.fecha_evento.localeCompare(b.fecha_evento):a.fecha_evento?-1:b.fecha_evento?1:0),publicaciones=avisos.filter(a=>a.tipo!=='tarea'),hoy=fechaBogota();
 const tarjeta=(a,tarea=false)=><article className="card" key={a.id}><small>{a.grado?`Grado ${a.grado}°`:'Todos los grados'}</small><h4>{a.titulo}</h4><p>{a.contenido}</p>{a.fecha_evento&&<b>{tarea?'Fecha de entrega':'Fecha'}: {a.fecha_evento}{tarea&&a.fecha_evento<hoy?' · Fecha vencida':tarea&&a.fecha_evento===hoy?' · Para hoy':''}</b>}</article>;
 return <section><h2>📚 Tareas y Avisos</h2><p>Información publicada para el grado de tu {referencia(hijo)} y para toda la institución.</p><section aria-label="Tareas pendientes"><h3>📚 Tareas pendientes</h3><p>Tareas publicadas por los profesores. Permanecen visibles mientras el profesor mantenga la publicación activa.</p>{tareas.length?tareas.map(a=>tarjeta(a,true)):<p>No hay tareas pendientes publicadas.</p>}</section><section aria-label="Avisos para la familia"><h3>📣 Avisos para la familia</h3>{publicaciones.length?publicaciones.map(a=>tarjeta(a)):<p>No hay avisos publicados.</p>}{mensajes.length>0&&<><h4>Mensajes aprobados de la comunidad</h4>{mensajes.map(m=><article className="card" key={m.id}><h4>{m.titulo}</h4><p>{m.contenido}</p></article>)}</>}</section></section>;
}
function HorarioAcudiente({datos}){
 const[hoy,setHoy]=useState(fechaBogota),hijo=datos.estudiante;
 const dia=new Date(hoy+'T12:00:00Z').getUTCDay(),bloques=['7:00–7:55','7:55–8:50','8:50–9:45','10:15–11:10','11:10–12:05','12:05–1:00'];
 const base=datos.horario_base.filter(h=>h.dia===dia),cambios=datos.horario_cambios.filter(h=>h.fecha===hoy);
 return <section><h2>🕒 Horario de mi {referencia(hijo)} · {hijo.grado}°</h2>{datos.horario_base.length?<><label>Fecha de consulta<input type="date" min={fechaMover(fechaBogota(),-7)} max={fechaMover(fechaBogota(),14)} value={hoy} onChange={e=>e.target.value&&setHoy(e.target.value)}/></label><h3>{dias[dia]} · {hoy}</h3>{dia===0||dia===6?<p>No hay clases regulares en esta fecha.</p>:<div className="guardianSchedule">{bloques.map((hora,i)=>{const cambio=cambios.find(h=>h.bloque===i+1),clase=cambio||base.find(h=>h.bloque===i+1);return <article className="card" key={hora}><b>{hora}</b><h3>{clase?.cancelada?'Clase cancelada':clase?.materia||'Sin clase registrada'}</h3>{clase?.profesor&&<p>Docente: {clase.profesor}</p>}{cambio&&<small>Cambio de horario{clase.aviso?`: ${clase.aviso}`:''}</small>}</article>})}</div>}</>:<p className="placeholder">La institución aún no ha publicado el horario para este grado.</p>}</section>;
}
const fechaMover=(fecha,n)=>{const d=new Date(fecha+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
function CuentaAcudiente({hijo}){
 const[password,setPassword]=useState(''),[confirmacion,setConfirmacion]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function cambiar(e){e.preventDefault();if(busy)return;setMsg('');if(password!==confirmacion){setMsg('Las contraseñas no coinciden.');return}setBusy(true);try{const{error}=await supabase.auth.updateUser({password});if(error)throw error;setPassword('');setConfirmacion('');setMsg(`✅ Contraseña actualizada. En adelante ingresa con el documento de tu ${referencia(hijo)} y esta nueva contraseña.`)}catch(e){setMsg('No se pudo cambiar la contraseña: '+e.message)}finally{setBusy(false)}}
 return <section><h2>🔐 Mi cuenta de acudiente</h2><article className="card"><p>Estudiante: <b>{hijo.nombre}</b></p><p>Usuario: <b>{hijo.documento}</b></p><p>Esta cuenta es independiente de la cuenta de Google del estudiante.</p><h3>Cambiar contraseña (opcional)</h3><form className="guardianPassword" onSubmit={cambiar}><label>Nueva contraseña<input type="password" autoComplete="new-password" required minLength={6} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Confirmar contraseña<input type="password" autoComplete="new-password" required minLength={6} maxLength={128} value={confirmacion} onChange={e=>setConfirmacion(e.target.value)}/></label><small>Al menos 6 caracteres. Puedes seguir usando tu contraseña actual si no deseas cambiarla.</small><button className="save" disabled={busy}>{busy?'Guardando…':'Guardar nueva contraseña'}</button></form>{msg&&<p className="notice" role="status">{msg}</p>}<p>Si olvidas la contraseña, solicita ayuda al profesor para restablecerla.</p></article></section>;
}
function EncuestasAcudiente({hijo}){
 const[datos,setDatos]=useState(null),[error,setError]=useState('');useEffect(()=>{let vigente=true;supabase.rpc('acudiente_encuestas').then(({data,error})=>{if(vigente){if(error)setError('No se pudieron consultar los resultados publicados.');else setDatos(data)}}).catch(()=>{if(vigente)setError('No se pudieron consultar los resultados publicados.')});return()=>{vigente=false}},[]);
 return <section><h2>📋 Resultados publicados</h2><p>Consulta los resultados compartidos con el grado de tu {referencia(hijo)}.</p>{error?<p className="error">{error}</p>:!datos?<p>Cargando resultados…</p>:<>{!datos.encuestas.length&&!datos.grammy&&<p>No hay resultados publicados todavía.</p>}{datos.encuestas.map(e=><article className="card" key={e.id}><h3>{e.titulo}</h3>{e.descripcion&&<p>{e.descripcion}</p>}{e.preguntas.map(p=><div key={p.id}><h4>{p.titulo}</h4><ol>{e.conteo.filter(v=>v.pregunta_id===p.id).map(v=><li key={v.candidato_id}>{v.nombre} · {v.grado}° · {v.votos} votos</li>)}</ol></div>)}</article>)}{datos.grammy&&<article className="card"><h3>🏆 Grammy de la Juventud</h3>{repartirPremios(datos.grammy.categorias,datos.grammy.conteo).map(r=><div key={r.categoria.id}><h4>{r.categoria.titulo}</h4>{r.ganadores.length?r.ganadores.map(g=><p key={g.candidato_id}>🏆 {g.nombre} · {g.grado}° · {g.votos} votos</p>):<p>{r.pendiente?'Desempate pendiente':'Sin ganador asignado'}</p>}</div>)}</article>}</>}</section>;
}
export default function VistaAcudiente({perfil}){
 const clave=`claudina-clean:pestana:acudiente:${perfil.id}`;
 const[tab,setTab]=useState(()=>{try{const t=localStorage.getItem(clave);return t==='calificaciones'?'aseo':tabs.some(([id])=>id===t)?t:'inicio'}catch{return'inicio'}}),[datos,setDatos]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function cargar(){setLoading(true);setError('');try{const{data,error}=await supabase.rpc('acudiente_contexto');if(error)throw error;setDatos(data)}catch(e){setError('No se pudo consultar la información: '+e.message)}finally{setLoading(false)}}
 useEffect(()=>{cargar()},[perfil.id]);

 function seleccionar(t){setTab(t);try{localStorage.setItem(clave,t)}catch{}}
 const hijo=datos?.estudiante,filas=datos?.participaciones||[],notas=notasConRecuperaciones(filas).filter(p=>p.notaEfectiva!=null),promedio=notas.length?(notas.reduce((n,p)=>n+Number(p.notaEfectiva),0)/notas.length).toFixed(2):'—',hoyDia=new Date(fechaBogota()+'T12:00:00Z').getUTCDay();
 return <main><header><img className="brandShield" src={escudo} alt="Escudo de Claudina Múnera"/><div><h1>Claudina Clean</h1><p>👨‍👩‍👧 Acudiente{hijo?` de ${hijo.nombre}`:''}</p></div><button className="logout" onClick={()=>supabase.auth.signOut()}>Salir</button></header><AlertaEvacuacion/><nav aria-label="Secciones del acudiente">{tabs.map(([id,t])=><button className={tab===id?'active':''} onClick={()=>seleccionar(id)} key={id}>{t.replace(/hijo/g,referencia(hijo))}</button>)}</nav>{loading?<section><p role="status">Consultando la información de tu {referencia(hijo)}…</p></section>:error?<section><p className="error">{error}</p><button onClick={cargar}>Reintentar</button></section>:hijo&&<><section className="guardianIdentity"><b>{hijo.nombre} · {hijo.grado}°</b><GeneroEstudiante ocultarDefinido estudiante={hijo} onGuardar={genero=>setDatos(d=>({...d,estudiante:{...d.estudiante,genero}}))}/><button onClick={cargar}>Actualizar información</button></section>{tab==='inicio'&&<section><div className="hero"><span>FAMILIAS QUE ACOMPAÑAN</span><h2>Mi {referencia(hijo)} en Claudina</h2><p>{hijo.nombre} · Grado {hijo.grado}°</p></div><article className="card"><h3>📅 Turnos de aseo</h3><p>{datos.turnos.length?datos.turnos.map(d=>dias[d]).join(', '):'Todavía no tiene turnos asignados.'}</p>{datos.turnos.includes(hoyDia)&&<p className="notice">Hoy le corresponde hacer el aseo.</p>}{filas[0]&&<p>Último aseo: {filas[0].fecha} · {estado[filas[0].estado]} · {filas[0].calificacion??'—'}/10</p>}<p>Promedio de aseo: <b>{promedio}/10</b></p><button onClick={()=>seleccionar('aseo')}>Ver aseo y evidencias</button></article><article className="card"><h3>Contacto escolar</h3><p>{hijo.email||'Correo institucional aún no registrado.'}</p><p>Consulta los avisos para acompañar las actividades del colegio.</p><button onClick={()=>seleccionar('avisos')}>Ver tareas y avisos</button></article></section>}{tab==='horario'&&<HorarioAcudiente datos={datos}/>} {tab==='aseo'&&<AseosAcudiente filas={filas} hijo={hijo}/>} {tab==='avisos'&&<AvisosAcudiente avisos={datos.avisos} mensajes={datos.mensajes} hijo={hijo}/>} {tab==='reportes'&&<section><h2>🚨 Reportes enviados por mi {referencia(hijo)}</h2><p>Seguimiento de los problemas de aseo o convivencia que el estudiante ha reportado.</p>{datos.reportes.length?datos.reportes.map(r=><article className="card" key={r.id}><h3>{r.tipo}</h3><p>{r.descripcion}</p><small>{new Date(r.created_at).toLocaleDateString('es-CO')} · {r.estado==='pendiente'?'Pendiente de revisión':r.estado==='revisado'?'Revisado':r.estado==='descartado'?'Descartado':r.estado}</small></article>):<p>No hay reportes enviados por el estudiante.</p>}</section>}{tab==='convivencia'&&<ConvivenciaEstudiante/>}{tab==='encuestas'&&<EncuestasAcudiente hijo={hijo}/>}{tab==='cuenta'&&<CuentaAcudiente hijo={hijo}/>}</>}<footer>Claudina Clean · C.E.R. Claudina Múnera <span className="designCredit">Designed by Ghost</span></footer></main>;
}
