import React,{useEffect,useMemo,useState}from'react';
import {supabase} from './lib/supabase';

const dias=[['Lun',1],['Mar',2],['Mié',3],['Jue',4],['Vie',5]];

function Login(){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[msg,setMsg]=useState('');const[loading,setLoading]=useState(false);async function entrar(e){e.preventDefault();setLoading(true);setMsg('');const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg('No fue posible iniciar sesión. Revisa correo y contraseña.');setLoading(false)}return <main className="loginPage"><header><div className="brand">✨</div><div><h1>Claudina Clean</h1><p>Convivimos, cuidamos y transformamos</p></div></header><section><div className="loginCard"><h2>Bienvenido</h2><form onSubmit={entrar}><label>Correo</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><label>Contraseña</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="save" disabled={loading}>{loading?'Ingresando…':'Ingresar'}</button>{msg&&<p className="error">{msg}</p>}</form></div></section></main>}

function Grupo({value,setValue}){return <div className="switch"><button className={value==='6'?'active':''} onClick={()=>setValue('6')}>6°</button><button className={value==='7-8'?'active':''} onClick={()=>setValue('7-8')}>7° y 8°</button></div>}

function EstudiantesAdmin(){const[lista,setLista]=useState([]);const[nombre,setNombre]=useState('');const[grado,setGrado]=useState('6');const[msg,setMsg]=useState('');async function cargar(){const{data}=await supabase.from('estudiantes').select('*').order('grado').order('nombre');setLista(data||[])}useEffect(()=>{cargar()},[]);async function agregar(e){e.preventDefault();if(!nombre.trim())return;const{error}=await supabase.from('estudiantes').insert({nombre:nombre.trim(),grado:Number(grado)});setMsg(error?error.message:'Estudiante agregado');if(!error){setNombre('');cargar()}}async function cambiar(id,campo,valor){const{error}=await supabase.from('estudiantes').update({[campo]:valor}).eq('id',id);if(error)setMsg(error.message);else cargar()}return <section><h2>👥 Estudiantes</h2><p>Agrega estudiantes y conserva como inactivos a quienes se retiren para no perder su historial.</p><form className="studentForm" onSubmit={agregar}><input placeholder="Nombre del estudiante" value={nombre} onChange={e=>setNombre(e.target.value)}/><select value={grado} onChange={e=>setGrado(e.target.value)}><option value="6">6°</option><option value="7">7°</option><option value="8">8°</option></select><button className="save">+ Agregar</button></form>{msg&&<p className="notice">{msg}</p>}<div className="studentList">{lista.map(s=><article className={'studentRow '+(!s.activo?'inactive':'')} key={s.id}><div><b>{s.nombre}</b><small>Grado {s.grado}° · {s.activo?'Activo':'Retirado'}</small></div><div className="rowActions"><select value={s.grado} onChange={e=>cambiar(s.id,'grado',Number(e.target.value))}><option value="6">6°</option><option value="7">7°</option><option value="8">8°</option></select><button onClick={()=>{const n=prompt('Nuevo nombre',s.nombre);if(n?.trim())cambiar(s.id,'nombre',n.trim())}}>✏️</button><button onClick={()=>cambiar(s.id,'activo',!s.activo)}>{s.activo?'⏸️':'▶️'}</button></div></article>)}</div></section>}

function Asignacion(){const[grupo,setGrupo]=useState('6');const[estudiantes,setEstudiantes]=useState([]);const[asigs,setAsigs]=useState([]);const[busy,setBusy]=useState('');async function cargar(){const{data:e}=await supabase.from('estudiantes').select('*').eq('activo',true).order('nombre');const{data:a}=await supabase.from('asignaciones').select('*');setEstudiantes(e||[]);setAsigs(a||[])}useEffect(()=>{cargar()},[]);const visibles=estudiantes.filter(s=>grupo==='6'?s.grado===6:[7,8].includes(s.grado));const tiene=(id,d)=>asigs.some(a=>a.estudiante_id===id&&a.dia===d);async function toggle(id,d){const key=id+d;setBusy(key);if(tiene(id,d)){await supabase.from('asignaciones').delete().eq('estudiante_id',id).eq('dia',d)}else{await supabase.from('asignaciones').insert({estudiante_id:id,dia:d})}await cargar();setBusy('')}return <section><h2>📅 Asignación de aseo</h2><p>Marca los días que le corresponden a cada estudiante. Los cambios se guardan inmediatamente.</p><Grupo value={grupo} setValue={setGrupo}/>{visibles.length===0?<div className="placeholder">Primero agrega estudiantes en 👥 Estudiantes.</div>:<div className="assignment"><div className="assignmentHead"><b>Estudiante</b>{dias.map(([n])=><b key={n}>{n}</b>)}</div>{visibles.map(s=><div className="assignmentRow" key={s.id}><span><b>{s.nombre}</b><small>{s.grado}°</small></span>{dias.map(([n,d])=><button aria-label={n} key={d} disabled={busy===s.id+d} className={tiene(s.id,d)?'dayOn':'dayOff'} onClick={()=>toggle(s.id,d)}>{tiene(s.id,d)?'✓':'○'}</button>)}</div>)}</div>}</section>}

function Hoy(){const[grupo,setGrupo]=useState('6');const[turno,setTurno]=useState([]);const dia=new Date().getDay();useEffect(()=>{async function cargar(){if(dia<1||dia>5){setTurno([]);return}const{data:a}=await supabase.from('asignaciones').select('estudiante_id').eq('dia',dia);const ids=(a||[]).map(x=>x.estudiante_id);if(!ids.length){setTurno([]);return}const{data:e}=await supabase.from('estudiantes').select('*').in('id',ids).eq('activo',true).order('nombre');setTurno(e||[])}cargar()},[dia]);const visibles=turno.filter(s=>grupo==='6'?s.grado===6:[7,8].includes(s.grado));return <section><div className="hero"><span>ASEO DE HOY</span><h2>{new Intl.DateTimeFormat('es-CO',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</h2></div><Grupo value={grupo} setValue={setGrupo}/>{visibles.length?<>{<h3>Turno de hoy</h3>}{visibles.map(s=><article className="card" key={s.id}><h3>{s.nombre} <small>· {s.grado}°</small></h3><p>El registro detallado de tareas, caritas y evidencias será el siguiente módulo.</p></article>)}</>:<div className="placeholder">🧹 No hay estudiantes asignados para hoy en este grupo.</div>}</section>}

function Profesor({perfil}){const[tab,setTab]=useState('hoy');return <main><header><div className="brand">✨</div><div><h1>Claudina Clean</h1><p>👨‍🏫 {perfil.nombre} · Administrador</p></div><button className="logout" onClick={()=>supabase.auth.signOut()}>Salir</button></header><nav>{[['hoy','🏠 Hoy'],['asignacion','📅 Asignación'],['estudiantes','👥 Estudiantes'],['reportes','🚨 Reportes'],['historial','📊 Historial']].map(([k,t])=><button key={k} onClick={()=>setTab(k)} className={tab===k?'active':''}>{t}</button>)}</nav>{tab==='hoy'&&<Hoy/>}{tab==='asignacion'&&<Asignacion/>}{tab==='estudiantes'&&<EstudiantesAdmin/>}{tab==='reportes'&&<section><h2>🚨 Reportes</h2><div className="placeholder">Los reportes estudiantiles se habilitarán después del registro diario.</div></section>}{tab==='historial'&&<section><h2>📊 Historial y estadísticas</h2><div className="placeholder">Se alimentará automáticamente con los registros diarios.</div></section>}<footer>Claudina Clean · C.E.R. Claudina Múnera</footer></main>}

function Estudiante({perfil}){return <main><header><div className="brand">✨</div><div><h1>Claudina Clean</h1><p>🎒 {perfil.nombre}</p></div><button className="logout" onClick={()=>supabase.auth.signOut()}>Salir</button></header><section><div className="hero"><span>HOY</span><h2>Cuidamos juntos nuestro salón</h2></div><div className="placeholder">Tu espacio de estudiante está siendo preparado.</div></section></main>}

export default function App(){const[session,setSession]=useState(null);const[perfil,setPerfil]=useState(null);const[loading,setLoading]=useState(true);useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);useEffect(()=>{async function cargar(){if(!session){setPerfil(null);setLoading(false);return}setLoading(true);const{data,error}=await supabase.from('perfiles').select('nombre,rol').eq('id',session.user.id).single();if(!error)setPerfil(data);setLoading(false)}cargar()},[session]);if(loading)return <div className="loading">✨ Cargando Claudina Clean…</div>;if(!session)return <Login/>;if(!perfil)return <main><section><div className="placeholder">Tu cuenta aún no tiene perfil autorizado.</div><button className="save" onClick={()=>supabase.auth.signOut()}>Salir</button></section></main>;return perfil.rol==='profesor'?<Profesor perfil={perfil}/>:<Estudiante perfil={perfil}/>}
