import React,{useEffect,useState} from 'react';
import {supabase} from './lib/supabase';

const nombres={evento:'📅 Evento próximo',tarea:'📚 Tarea',motivacion:'✨ Motivación'};
const formatoFecha=fecha=>new Intl.DateTimeFormat('es-CO',{day:'numeric',month:'long',year:'numeric'}).format(new Date(`${fecha}T12:00:00`));

export function AvisosEstudiante(){
  const[avisos,setAvisos]=useState([]),[error,setError]=useState(''),[cargando,setCargando]=useState(true);
  useEffect(()=>{let activo=true;async function cargar(){const{data,error}=await supabase.from('avisos').select('id,tipo,titulo,contenido,grado,fecha_evento,created_at').eq('publicado',true).order('created_at',{ascending:false}).limit(30);if(activo){setAvisos(data||[]);setError(error?.message||'');setCargando(false)}}cargar();return()=>{activo=false}},[]);
  return <section className="avisosSection" aria-label="Avisos"><h3>📣 Avisos para ti</h3>{cargando?<p>Cargando avisos…</p>:error?<p className="error">No se pudieron cargar los avisos: {error}</p>:avisos.length?<div className="avisosList">{avisos.map(a=><article className="avisoCard" key={a.id}><div className="avisoMeta"><span>{nombres[a.tipo]}</span><span>{a.grado?`${a.grado}°`:'Todos los grados'}</span></div><h4>{a.titulo}</h4><p>{a.contenido}</p>{a.fecha_evento&&<strong>Fecha: {formatoFecha(a.fecha_evento)}</strong>}</article>)}</div>:<p className="placeholder">Todavía no hay avisos para tu grado.</p>}</section>;
}

export function AvisosProfesor(){
  const[avisos,setAvisos]=useState([]),[tipo,setTipo]=useState('evento'),[titulo,setTitulo]=useState(''),[contenido,setContenido]=useState(''),[grado,setGrado]=useState('todos'),[fecha,setFecha]=useState(''),[msg,setMsg]=useState(''),[cargando,setCargando]=useState(true),[busy,setBusy]=useState(false);
  async function cargar(){const{data,error}=await supabase.from('avisos').select('*').order('created_at',{ascending:false}).limit(100);setAvisos(data||[]);setCargando(false);if(error)setMsg('No se pudieron cargar los avisos: '+error.message)}
  useEffect(()=>{cargar()},[]);
  async function crear(e){e.preventDefault();if(busy)return;setBusy(true);setMsg('');const{data:{user},error:authError}=await supabase.auth.getUser();if(authError||!user){setMsg('Tu sesión expiró. Ingresa de nuevo.');setBusy(false);return}const{error}=await supabase.from('avisos').insert({tipo,titulo:titulo.trim(),contenido:contenido.trim(),grado:grado==='todos'?null:Number(grado),fecha_evento:fecha||null,creado_por:user.id});if(error)setMsg('No se pudo publicar: '+error.message);else{setTitulo('');setContenido('');setFecha('');setMsg('✅ Aviso publicado.');await cargar()}setBusy(false)}
  async function cambiar(a){setBusy(true);setMsg('');const{error}=await supabase.from('avisos').update({publicado:!a.publicado}).eq('id',a.id);setMsg(error?'No se pudo actualizar: '+error.message:!a.publicado?'Aviso publicado.':'Aviso ocultado.');if(!error)await cargar();setBusy(false)}
  async function eliminar(a){if(!window.confirm(`¿Borrar definitivamente el aviso «${a.titulo}»?`))return;setBusy(true);setMsg('');const{error}=await supabase.from('avisos').delete().eq('id',a.id);setMsg(error?'No se pudo borrar: '+error.message:'Aviso borrado.');if(!error)await cargar();setBusy(false)}
  return <section><h2>📣 Avisos</h2><p>Publica eventos, tareas o mensajes para todos los grados o para uno en particular. Aparecerán en Inicio de los estudiantes.</p><form className="avisoForm card" onSubmit={crear}><label>Tipo<select value={tipo} onChange={e=>setTipo(e.target.value)}><option value="evento">Evento próximo</option><option value="tarea">Tarea</option><option value="motivacion">Frase de motivación</option></select></label><label>Destinatarios<select value={grado} onChange={e=>setGrado(e.target.value)}><option value="todos">Todos los grados</option>{Array.from({length:8},(_,i)=><option value={i+1} key={i+1}>Grado {i+1}°</option>)}</select></label><label>Título<input value={titulo} onChange={e=>setTitulo(e.target.value)} maxLength={120} required placeholder="Ej. Salida pedagógica"/></label><label>Mensaje<textarea value={contenido} onChange={e=>setContenido(e.target.value)} maxLength={1000} required placeholder="Escribe el aviso para los estudiantes"/></label>{tipo!=='motivacion'&&<label>Fecha del evento o entrega (opcional)<input type="date" value={fecha} onChange={e=>setFecha(e.target.value)}/></label>}<button className="save" disabled={busy||!titulo.trim()||!contenido.trim()}>{busy?'Guardando…':'Publicar aviso'}</button></form>{msg&&<p role="status" className="notice">{msg}</p>}<h3>Avisos creados</h3>{cargando?<p>Cargando…</p>:avisos.length?<div className="avisosList">{avisos.map(a=><article className="avisoCard" key={a.id}><div className="avisoMeta"><span>{nombres[a.tipo]} · {a.grado?`${a.grado}°`:'Todos'}</span><span>{a.publicado?'Publicado':'Oculto'}</span></div><h4>{a.titulo}</h4><p>{a.contenido}</p>{a.fecha_evento&&<strong>Fecha: {formatoFecha(a.fecha_evento)}</strong>}<div className="avisoActions"><button disabled={busy} onClick={()=>cambiar(a)}>{a.publicado?'Ocultar':'Volver a publicar'}</button><button disabled={busy} className="dangerButton" onClick={()=>eliminar(a)}>Borrar</button></div></article>)}</div>:<p className="placeholder">Aún no hay avisos.</p>}</section>;
}
