import React,{useEffect,useState} from 'react';
import {supabase} from './lib/supabase';
import Grammy from './Grammy';
import './Encuestas.css';

const gradosTexto=grados=>(grados||[]).map(g=>`${g}°`).join(', ');
const nueva=()=>({titulo:'',descripcion:'',grados_participantes:[6,7,8],grados_candidatos:[6,7,8]});
const etiqueta={borrador:'Borrador',abierta:'Abierta',cerrada:'Cerrada'};
function Grados({titulo,value,onChange,disabled}){
 return <fieldset className="surveyGrades"><legend>{titulo}</legend>{Array.from({length:8},(_,i)=>i+1).map(g=><label key={g}><input type="checkbox" disabled={disabled} checked={value.includes(g)} onChange={()=>onChange(value.includes(g)?value.filter(n=>n!==g):[...value,g].sort((a,b)=>a-b))}/>{g}°</label>)}</fieldset>;
}
function EditorEncuesta({datos,onGuardar,onCancelar,busy}){
 const[form,setForm]=useState(datos);
 return <form className="card surveyEditor" onSubmit={e=>{e.preventDefault();onGuardar(form)}}><h3>{datos.id?'Editar encuesta':'Nueva encuesta'}</h3><label>Título<input required maxLength={150} value={form.titulo} disabled={busy} onChange={e=>setForm(v=>({...v,titulo:e.target.value}))}/></label><label>Descripción<textarea maxLength={1000} value={form.descripcion} disabled={busy} onChange={e=>setForm(v=>({...v,descripcion:e.target.value}))}/></label><Grados titulo="Grados que pueden responder" value={form.grados_participantes} onChange={g=>setForm(v=>({...v,grados_participantes:g}))} disabled={busy}/><Grados titulo="Grados que aparecen como candidatos" value={form.grados_candidatos} onChange={g=>setForm(v=>({...v,grados_candidatos:g}))} disabled={busy}/><p><small>Se mostrarán los nombres de estudiantes activos de los grados elegidos.</small></p><div className="chips"><button className="save" disabled={busy||!form.titulo.trim()||!form.grados_participantes.length||!form.grados_candidatos.length}>Guardar encuesta</button><button type="button" disabled={busy} onClick={onCancelar}>Cancelar</button></div></form>;
}
function EditorPregunta({pregunta,onGuardar,onCancelar,busy}){
 const[form,setForm]=useState(pregunta);
 return <form className="card surveyEditor" onSubmit={e=>{e.preventDefault();onGuardar(form)}}><h3>{pregunta.id?'Editar pregunta':'Agregar pregunta'}</h3><label>Pregunta<input required maxLength={200} value={form.titulo} disabled={busy} onChange={e=>setForm(v=>({...v,titulo:e.target.value}))} placeholder="¿Quién es el compañero más…?"/></label><label>Descripción opcional<textarea maxLength={500} value={form.descripcion} disabled={busy} onChange={e=>setForm(v=>({...v,descripcion:e.target.value}))}/></label><div className="chips"><button className="save" disabled={busy||!form.titulo.trim()}>Guardar pregunta</button><button type="button" disabled={busy} onClick={onCancelar}>Cancelar</button></div></form>;
}
function DetalleEncuesta({id,profesor,onVolver,onCambiar}){
 const[datos,setDatos]=useState(null),[votos,setVotos]=useState({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[msg,setMsg]=useState(''),[editor,setEditor]=useState(false),[pregunta,setPregunta]=useState(null);
 useEffect(()=>{let vigente=true;supabase.rpc('encuesta_contexto',{encuesta:id}).then(({data,error})=>{if(!vigente)return;if(error)setError(error.message);else{setDatos(data);setVotos(Object.fromEntries(Object.entries(data.mis_respuestas||{}).map(([k,v])=>[k,v.candidato_id])))}setLoading(false)});return()=>{vigente=false}},[id]);
 async function cargar(){const{data,error}=await supabase.rpc('encuesta_contexto',{encuesta:id});if(error){setError(error.message);return}setDatos(data);setVotos(Object.fromEntries(Object.entries(data.mis_respuestas||{}).map(([k,v])=>[k,v.candidato_id])));setError('')}
 async function ejecutar(nombre,args,mensaje){if(busy)return false;setBusy(true);setMsg('');try{const{error}=await supabase.rpc(nombre,args);if(error){setMsg(error.message);return false}setMsg(mensaje);await cargar();onCambiar();return true}catch(e){setMsg('No se pudo completar: '+e.message);return false}finally{setBusy(false)}}
 async function administrar(accion){await ejecutar('encuesta_administrar',{encuesta:id,accion},accion==='abrir'?'✅ Encuesta abierta.':accion==='cerrar'?'✅ Encuesta cerrada.':accion==='publicar'?'✅ Resultados publicados.':'Resultados ocultos.')}
 async function guardarEncuesta(form){if(await ejecutar('encuesta_guardar',{encuesta:id,datos:form},'✅ Encuesta actualizada.'))setEditor(false)}
 async function guardarPregunta(form){if(await ejecutar('encuesta_pregunta_guardar',{encuesta:id,pregunta:form.id||null,datos:form},'✅ Pregunta guardada.'))setPregunta(null)}
 async function eliminar(p){if(!window.confirm(`¿Eliminar la pregunta «${p.titulo}»?`))return;await ejecutar('encuesta_pregunta_eliminar',{encuesta:id,pregunta:p.id},'Pregunta eliminada.')}
 async function responder(e){e.preventDefault();await ejecutar('encuesta_responder',{encuesta:id,elecciones:Object.fromEntries(datos.preguntas.map(p=>[p.id,votos[p.id]||'']))},'✅ Tus respuestas quedaron guardadas. Puedes cambiarlas hasta el cierre.')}
 if(loading)return <section><p role="status">Cargando encuesta…</p></section>;
 if(error||!datos)return <section><button onClick={onVolver}>← Volver a Encuestas</button><p className="error">{error||'Encuesta no disponible.'}</p><button onClick={cargar}>Reintentar</button></section>;
 const ficha=datos.encuesta,admin=profesor&&datos.profesor,abierta=ficha.estado==='abierta';
 return <section className="surveyDetail"><button type="button" disabled={busy} onClick={onVolver}>← Volver a Encuestas</button><div className="hero"><span>📋 ENCUESTA · {etiqueta[ficha.estado]}</span><h2>{ficha.titulo}</h2>{ficha.descripcion&&<p>{ficha.descripcion}</p>}</div><p>Participan: {gradosTexto(ficha.grados_participantes)} · Candidatos: {gradosTexto(ficha.grados_candidatos)}</p>{msg&&<p className="notice" role="status">{msg}</p>}
 {admin&&<article className="card"><h3>Administrar encuesta</h3><p>{datos.participantes||0} estudiantes han respondido · {datos.preguntas.length} preguntas</p><div className="chips"><button disabled={busy||abierta||!datos.preguntas.length} onClick={()=>administrar('abrir')}>{ficha.estado==='cerrada'?'Reabrir encuesta':'Abrir encuesta'}</button><button disabled={busy||!abierta} onClick={()=>administrar('cerrar')}>Cerrar encuesta</button><button disabled={busy||ficha.estado!=='cerrada'||ficha.resultados_publicados} onClick={()=>administrar('publicar')}>Publicar resultados</button><button disabled={busy||!ficha.resultados_publicados} onClick={()=>administrar('ocultar')}>Ocultar resultados</button><button disabled={busy||!datos.editable} onClick={()=>{setPregunta(null);setEditor(true)}}>Editar encuesta y grados</button><button disabled={busy||!datos.editable} onClick={()=>{setEditor(false);setPregunta({titulo:'',descripcion:''})}}>+ Agregar pregunta</button><button disabled={busy} onClick={cargar}>Actualizar conteo</button></div><small>{datos.editable?'Agrega y revisa las preguntas antes de abrir la encuesta.':'Las preguntas y grados se conservan al recibir respuestas. Puedes crear otra encuesta para hacer cambios.'} Los estudiantes ven el conteo cuando publiques los resultados.</small></article>}
 {editor&&<EditorEncuesta key={ficha.id} datos={ficha} onGuardar={guardarEncuesta} onCancelar={()=>setEditor(false)} busy={busy}/>}
 {pregunta&&<EditorPregunta key={pregunta.id||'nueva'} pregunta={pregunta} onGuardar={guardarPregunta} onCancelar={()=>setPregunta(null)} busy={busy}/>}
 {!admin&&<p className="notice">{datos.puede_responder?'Elige un compañero por pregunta. Puedes dejar preguntas sin responder y cambiar tus elecciones hasta el cierre.':abierta?'Tu cuenta puede consultar esta encuesta, pero no responderla.':'Esta encuesta está cerrada. Puedes consultar tus respuestas; ya no se pueden modificar.'}</p>}
 <form onSubmit={responder}>{!datos.preguntas.length&&<article className="card"><p>Agrega la primera pregunta para preparar la encuesta.</p></article>}{datos.preguntas.map((p,i)=>{
 const filas=(datos.conteo||[]).filter(v=>v.pregunta_id===p.id),max=filas[0]?.votos;
 const respuesta=datos.mis_respuestas?.[p.id];
 return <article className="card" key={p.id}><h3>{i+1}. {p.titulo}</h3>{p.descripcion&&<p>{p.descripcion}</p>}{admin?<div className="chips"><button type="button" disabled={busy||!datos.editable} onClick={()=>{setEditor(false);setPregunta({...p})}}>Editar pregunta</button><button type="button" className="dangerButton" disabled={busy||!datos.editable} onClick={()=>eliminar(p)}>Eliminar pregunta</button></div>:datos.puede_responder?<label>Elige un compañero<select disabled={busy} value={votos[p.id]||''} onChange={e=>setVotos(v=>({...v,[p.id]:e.target.value}))}><option value="">Sin respuesta</option>{votos[p.id]&&!datos.candidatos.some(s=>s.id===votos[p.id])&&<option value={votos[p.id]}>{respuesta?.nombre||'Estudiante ya no disponible'} · Cambia o elimina esta respuesta</option>}{datos.candidatos.map(s=><option value={s.id} key={s.id}>{s.nombre} · {s.grado}°</option>)}</select></label>:<p>Tu respuesta: <b>{respuesta?`${respuesta.nombre} · ${respuesta.grado}°`:'Sin respuesta'}</b></p>}
 {datos.conteo!==null&&<div className="surveyResults"><h4>{admin&&!ficha.resultados_publicados?'Conteo reservado a profesores':'Resultados'}</h4>{filas.length?<ol>{filas.map(v=><li key={v.candidato_id} className={v.votos===max?'surveyLeader':''}><span>{v.nombre} · {v.grado}°</span><b>{v.votos} {v.votos===1?'voto':'votos'}</b>{v.votos===max&&<small>Mayor votación{filas.filter(f=>f.votos===max).length>1?' · Empate':''}</small>}</li>)}</ol>:<p>Sin respuestas en esta pregunta.</p>}</div>}
 </article>})}{!admin&&datos.puede_responder&&datos.preguntas.length>0&&<button className="save" disabled={busy}>{busy?'Guardando…':'💾 Guardar mis respuestas'}</button>}</form>
 {!admin&&datos.conteo===null&&<p>El profesor aún no ha publicado los resultados.</p>}</section>;
}
export default function Encuestas({profesor=false,grado}){
 const[lista,setLista]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[seleccion,setSeleccion]=useState(null),[creando,setCreando]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function cargar(){try{const{data,error}=await supabase.rpc('encuestas_listar');if(error)setError('No se pudieron cargar las encuestas: '+error.message);else{setLista(data||[]);setError('')}}catch(e){setError('No se pudieron cargar las encuestas: '+e.message)}finally{setLoading(false)}}
 useEffect(()=>{cargar()},[]);
 async function crear(form){if(busy)return;setBusy(true);setMsg('');try{const{data,error}=await supabase.rpc('encuesta_guardar',{encuesta:null,datos:form});if(error)setMsg(error.message);else{setCreando(false);await cargar();setSeleccion(data)}}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 if(seleccion==='grammy')return <><section><button onClick={()=>setSeleccion(null)}>← Volver a Encuestas</button></section><Grammy profesor={profesor}/></>;
 if(seleccion)return <DetalleEncuesta key={seleccion} id={seleccion} profesor={profesor} onVolver={()=>{setSeleccion(null);cargar()}} onCambiar={cargar}/>;
 const abiertas=lista.filter(e=>e.estado==='abierta'),cerradas=lista.filter(e=>e.estado==='cerrada'),borradores=lista.filter(e=>e.estado==='borrador');
 const tarjeta=e=><article className="card surveyCard" key={e.id}><div><h3>{e.titulo}</h3><span className={'surveyBadge '+e.estado}>{etiqueta[e.estado]}</span></div>{e.descripcion&&<p>{e.descripcion}</p>}<p>{e.preguntas} preguntas · Participan: {gradosTexto(e.grados_participantes)}</p><small>Candidatos: {gradosTexto(e.grados_candidatos)}{e.resultados_publicados?' · Resultados publicados':''}</small><button onClick={()=>setSeleccion(e.id)}>{profesor?'Administrar encuesta':e.estado==='abierta'?'Responder encuesta':'Ver encuesta y mis respuestas'}</button></article>;
 return <section><div className="hero"><span>📋 PARTICIPACIÓN CLAUDINISTA</span><h2>Encuestas</h2><p>Elige a tus compañeros y participa en las decisiones del colegio.</p></div><button type="button" disabled={loading||busy} onClick={cargar}>Actualizar encuestas</button>{profesor&&<button className="save" disabled={!!error||loading} onClick={()=>{setMsg('');setCreando(true)}}>+ Crear encuesta</button>}{creando&&<EditorEncuesta datos={nueva()} onGuardar={crear} onCancelar={()=>setCreando(false)} busy={busy}/>} {msg&&<p className="notice" role="status">{msg}</p>}{loading?<p role="status">Cargando encuestas…</p>:error?<article className="card"><p className="error">{error}</p>{profesor&&<p>Para habilitar este módulo, ejecuta la actualización <b>encuestas.sql</b> en Supabase.</p>}<button onClick={cargar}>Reintentar</button></article>:<><h3>Encuestas abiertas</h3>{abiertas.length?abiertas.map(tarjeta):<p className="placeholder">No tienes encuestas abiertas en este momento.</p>}{profesor&&<><h3>En preparación</h3>{borradores.length?borradores.map(tarjeta):<p>No hay borradores.</p>}</>}</>}
 <h3>Encuestas anteriores</h3>{cerradas.map(tarjeta)}{(profesor||[6,7,8].includes(Number(grado)))&&<article className="card surveyCard"><h3>🏆 Grammy de la Juventud Claudinista</h3><p>Consulta la votación y los premios que ya realizamos.</p><button onClick={()=>setSeleccion('grammy')}>Ver Grammy y resultados</button></article>}{!cerradas.length&&!profesor&&![6,7,8].includes(Number(grado))&&<p>Todavía no tienes encuestas anteriores.</p>}</section>;
}
