import React,{useEffect,useMemo,useState} from 'react';
import {supabase} from './lib/supabase';

const dias=['Lunes','Martes','Miércoles','Jueves','Viernes'];
const horas=['7:00–7:55','7:55–8:50','8:50–9:45','10:15–11:10','11:10–12:05','12:05–1:00'];
const materias=['','Matemáticas','Inglés','Tecnología, informática y emprendimiento','Español','Ciencias Naturales','Ciencias Sociales','Educación Ética','Educación Religiosa'];
const docente=m=>['Matemáticas','Inglés','Tecnología, informática y emprendimiento'].includes(m)?'Gustavo':m?'Johana':'';
const hoyBogota=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bogota',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const fechaSemana=(lunes,offset)=>{const d=new Date(`${lunes}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+offset);return d.toISOString().slice(0,10)};
const inicioSemana=fecha=>{const d=new Date(`${fecha}T12:00:00Z`);d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));return d.toISOString().slice(0,10)};
const key=(g,d,b)=>`${g}-${d}-${b}`;

export default function Horario({grupoInicial='6',editable=false}){
  const[grupo,setGrupo]=useState(grupoInicial),[filtroProfesor,setFiltroProfesor]=useState(''),[lunes,setLunes]=useState(()=>inicioSemana(hoyBogota()));
  const[base,setBase]=useState([]),[cambios,setCambios]=useState([]),[editor,setEditor]=useState(null),[materia,setMateria]=useState(''),[profesor,setProfesor]=useState(''),[aviso,setAviso]=useState(''),[cancelada,setCancelada]=useState(false),[msg,setMsg]=useState(''),[cargando,setCargando]=useState(true);
  async function cargar(){setCargando(true);const [{data:b,error:e1},{data:c,error:e2}]=await Promise.all([supabase.from('horario_base').select('*'),supabase.from('horario_cambios').select('*').gte('fecha',lunes).lte('fecha',fechaSemana(lunes,4))]);setBase(b||[]);setCambios(c||[]);setMsg(e1||e2?'Para activar el horario, ejecuta horario-temporal.sql en Supabase. '+(e1||e2).message:'');setCargando(false)}
  useEffect(()=>{cargar()},[lunes]);
  const baseMap=useMemo(()=>Object.fromEntries(base.map(x=>[key(x.grupo,x.dia,x.bloque),x])),[base]);
  const cambioMap=useMemo(()=>Object.fromEntries(cambios.map(x=>[key(x.grupo,new Date(`${x.fecha}T12:00:00Z`).getUTCDay(),x.bloque),x])),[cambios]);
  const profesores=useMemo(()=>[...new Set([...base,...cambios].map(x=>x.profesor?.trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')),[base,cambios]);
  const clasesProfesor=useMemo(()=>{if(!filtroProfesor)return [];const resultado=[];for(let d=1;d<=5;d++)for(let b=1;b<=6;b++)for(const g of ['6','7-8']){const cambio=cambioMap[key(g,d,b)],clase=cambio||baseMap[key(g,d,b)];if(clase&&!clase.cancelada&&clase.materia&&clase.profesor?.trim()===filtroProfesor)resultado.push({...clase,grupo:g,dia:d,bloque:b,fecha:fechaSemana(lunes,d-1),cambio:!!cambio})}return resultado},[filtroProfesor,baseMap,cambioMap,lunes]);
  function abrir(d,b,modo){const actual=modo==='cambio'?cambioMap[key(grupo,d,b)]:baseMap[key(grupo,d,b)];setEditor({dia:d,bloque:b,modo});setMateria(actual?.materia||'');setProfesor(actual?.profesor||'');setAviso(actual?.aviso||'');setCancelada(!!actual?.cancelada);setMsg('')}
  async function guardar(e){e.preventDefault();if(!editor)return;const {dia,bloque,modo}=editor;const fecha=fechaSemana(lunes,dia-1);
    if(!cancelada&&profesor.trim()&&materia.trim()){
      const otro=grupo==='6'?'7-8':'6';const otraExcepcion=cambioMap[key(otro,dia,bloque)];const otra=otraExcepcion||baseMap[key(otro,dia,bloque)];
      if(otra&&!otra.cancelada&&otra.profesor?.trim().toLowerCase()===profesor.trim().toLowerCase()){setMsg(`⚠️ ${profesor} ya tiene clase con ${otro==='6'?'6.º':'7.º y 8.º'} en este bloque. Ajusta primero uno de los horarios.`);return}
    }
    const tabla=modo==='base'?'horario_base':'horario_cambios';const datos={grupo,dia,bloque,materia:materia.trim(),profesor:profesor.trim(),updated_at:new Date().toISOString()};if(modo==='cambio'){delete datos.dia;datos.fecha=fecha;datos.aviso=aviso.trim();datos.cancelada=cancelada}
    const {error}=await supabase.from(tabla).upsert(datos,{onConflict:modo==='base'?'grupo,dia,bloque':'fecha,grupo,bloque'});if(error){setMsg(error.message);return}setEditor(null);await cargar();setMsg('✅ Horario guardado y visible para estudiantes y profesores.')}
  async function quitarCambio(){const {dia,bloque}=editor;const {error}=await supabase.from('horario_cambios').delete().eq('fecha',fechaSemana(lunes,dia-1)).eq('grupo',grupo).eq('bloque',bloque);if(error){setMsg(error.message);return}setEditor(null);await cargar();setMsg('Cambio retirado: vuelve a aparecer el horario habitual.')}
  return <section><h2>📅 Horario de clases</h2><p>Horario temporal de 6.º y del grupo conjunto 7.º–8.º. Las novedades de esta semana aparecen resaltadas.</p><div className="scheduleControls"><div className="switch"><button className={grupo==='6'?'active':''} onClick={()=>{setGrupo('6');setEditor(null)}}>6.º</button><button className={grupo==='7-8'?'active':''} onClick={()=>{setGrupo('7-8');setEditor(null)}}>7.º y 8.º</button></div>{editable&&<label className="teacherScheduleFilter">Profesor<select value={filtroProfesor} onChange={e=>{setFiltroProfesor(e.target.value);setEditor(null)}}><option value="">Todos los profesores</option>{profesores.map(nombre=><option value={nombre} key={nombre}>{nombre}</option>)}</select></label>}<button onClick={()=>setLunes(fechaSemana(lunes,-7))}>← Anterior</button><strong>{lunes} a {fechaSemana(lunes,4)}</strong><button onClick={()=>setLunes(fechaSemana(lunes,7))}>Siguiente →</button></div>
    {msg&&<p className="notice" role="status">{msg}</p>}{cargando?<div className="placeholder">Cargando horario…</div>:filtroProfesor?<div className="card"><h3>Clases de {filtroProfesor} esta semana</h3>{clasesProfesor.length?<div className="gradesTableWrap"><table className="gradesTable"><thead><tr><th>Día</th><th>Hora</th><th>Grupo</th><th>Materia</th><th>Novedad</th></tr></thead><tbody>{clasesProfesor.map(x=><tr key={`${x.fecha}-${x.grupo}-${x.bloque}`}><td>{dias[x.dia-1]} {x.fecha}</td><td>{horas[x.bloque-1]}</td><td>{x.grupo==='6'?'6.º':'7.º y 8.º'}</td><td>{x.materia}</td><td>{x.cambio?`🔔 ${x.aviso||'Cambio de esta fecha'}`:'—'}</td></tr>)}</tbody></table></div>:<p>No tiene clases asignadas en esta semana.</p>}</div>:<div className="scheduleDays">{dias.map((nombre,i)=>{const dia=i+1,fecha=fechaSemana(lunes,i);return <article className="card scheduleDay" key={dia}><h3>{nombre} <small>{fecha}</small></h3>{horas.map((hora,j)=>{const bloque=j+1,b=baseMap[key(grupo,dia,bloque)],c=cambioMap[key(grupo,dia,bloque)],dato=c||b;return <div className={'scheduleSlot '+(c?'scheduleChanged':'')} key={bloque}><span><b>{bloque}.ª</b><small>{hora}</small></span><div><b>{c?.cancelada?'Clase cancelada':dato?.materia||'Sin clase asignada'}</b>{!c?.cancelada&&dato?.profesor&&<small>Profe {dato.profesor}</small>}{c&&<small>🔔 Cambio de esta semana {c.aviso&&`· ${c.aviso}`}</small>}</div>{editable&&<div className="scheduleActions"><button onClick={()=>abrir(dia,bloque,'cambio')}>Cambiar día</button><button onClick={()=>abrir(dia,bloque,'base')}>Editar habitual</button></div>}</div>})}</article>})}</div>}
    {editable&&editor&&<form className="card scheduleEditor" onSubmit={guardar}><h3>{editor.modo==='base'?'Editar horario habitual':'Cambio solo para esta fecha'} · {dias[editor.dia-1]} {fechaSemana(lunes,editor.dia-1)} · {editor.bloque}.ª hora</h3><label>Materia<select value={materia} onChange={e=>{setMateria(e.target.value);setProfesor(docente(e.target.value))}}>{materias.map(x=><option key={x} value={x}>{x||'Sin clase asignada'}</option>)}</select></label><label>Profesor<input value={profesor} onChange={e=>setProfesor(e.target.value)} placeholder="Nombre del profesor o reemplazo"/></label>{editor.modo==='cambio'&&<><label>Motivo o aviso<input value={aviso} onChange={e=>setAviso(e.target.value)} placeholder="Ej. profesor ausente; trabajo autónomo"/></label><label><input type="checkbox" checked={cancelada} onChange={e=>setCancelada(e.target.checked)}/> Clase cancelada</label></>}<div className="scheduleActions"><button className="save" type="submit">Guardar y publicar</button>{editor.modo==='cambio'&&cambioMap[key(grupo,editor.dia,editor.bloque)]&&<button type="button" onClick={quitarCambio}>Quitar cambio</button>}<button type="button" onClick={()=>setEditor(null)}>Cerrar</button></div></form>}
    <p className="taskHelp">Descanso pedagógico: 9:45–10:15. Las horas 5.ª y 6.ª están disponibles si se asignan nuevas clases.</p>
  </section>;
}
