import React,{useEffect,useMemo,useState} from 'react';
import {supabase} from './lib/supabase';

const dias=['Lunes','Martes','Miércoles','Jueves','Viernes'];
const horas=['7:00–7:55','7:55–8:50','8:50–9:45','10:15–11:10','11:10–12:05','12:05–1:00'];
const materias=['','Matemáticas','Inglés','Tecnología, informática y emprendimiento','Español','Ciencias Naturales','Ciencias Sociales','Educación Ética','Educación Religiosa'];
const docente=m=>['Matemáticas','Inglés','Tecnología, informática y emprendimiento'].includes(m)?'Gustavo':m?'Johana':'';
const hoyBogota=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bogota',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const fechaSemana=(lunes,offset)=>{const d=new Date(`${lunes}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+offset);return d.toISOString().slice(0,10)};
const inicioSemana=fecha=>{const d=new Date(`${fecha}T12:00:00Z`);d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));return d.toISOString().slice(0,10)};
const diaActual=()=>new Date(`${hoyBogota()}T12:00:00Z`).getUTCDay();
const semanaInicial=()=>{const fecha=hoyBogota(),lunes=inicioSemana(fecha);return diaActual()>5?fechaSemana(lunes,7):lunes};
const diaInicial=()=>diaActual()>=1&&diaActual()<=5?diaActual():1;
const key=(g,d,b)=>`${g}-${d}-${b}`;

export default function Horario({grupoInicial='6',editable=false}){
  const[grupo,setGrupo]=useState(grupoInicial),[filtroProfesor,setFiltroProfesor]=useState(''),[vistaDocente,setVistaDocente]=useState('dia'),[lunes,setLunes]=useState(semanaInicial),[diaSeleccionado,setDiaSeleccionado]=useState(diaInicial);
  const[base,setBase]=useState([]),[cambios,setCambios]=useState([]),[editor,setEditor]=useState(null),[materia,setMateria]=useState(''),[profesor,setProfesor]=useState(''),[aviso,setAviso]=useState(''),[cancelada,setCancelada]=useState(false),[msg,setMsg]=useState(''),[cargando,setCargando]=useState(true);
  async function cargar(){setCargando(true);const [{data:b,error:e1},{data:c,error:e2}]=await Promise.all([supabase.from('horario_base').select('*'),supabase.from('horario_cambios').select('*').gte('fecha',lunes).lte('fecha',fechaSemana(lunes,4))]);setBase(b||[]);setCambios(c||[]);setMsg(e1||e2?'Para activar el horario, ejecuta horario-temporal.sql en Supabase. '+(e1||e2).message:'');setCargando(false)}
  useEffect(()=>{cargar()},[lunes]);
  const baseMap=useMemo(()=>Object.fromEntries(base.map(x=>[key(x.grupo,x.dia,x.bloque),x])),[base]);
  const cambioMap=useMemo(()=>Object.fromEntries(cambios.map(x=>[key(x.grupo,new Date(`${x.fecha}T12:00:00Z`).getUTCDay(),x.bloque),x])),[cambios]);
  const profesores=useMemo(()=>[...new Set([...base,...cambios].map(x=>x.profesor?.trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')),[base,cambios]);
  const clasesProfesor=useMemo(()=>{if(!filtroProfesor)return [];const resultado=[];for(let d=1;d<=5;d++)for(let b=1;b<=6;b++)for(const g of ['6','7-8']){const cambio=cambioMap[key(g,d,b)],clase=cambio||baseMap[key(g,d,b)];if(clase&&!clase.cancelada&&clase.materia&&clase.profesor?.trim()===filtroProfesor)resultado.push({...clase,grupo:g,dia:d,bloque:b,fecha:fechaSemana(lunes,d-1),cambio:!!cambio})}return resultado},[filtroProfesor,baseMap,cambioMap,lunes]);
  useEffect(()=>{if(editor)document.getElementById('schedule-edit-form')?.scrollIntoView({behavior:'smooth',block:'start'})},[editor]);
  function abrir(d,b,modo,g=grupo){setGrupo(g);const actual=modo==='cambio'?cambioMap[key(g,d,b)]:baseMap[key(g,d,b)];setEditor({dia:d,bloque:b,modo});setMateria(actual?.materia||'');setProfesor(actual?.profesor||'');setAviso(actual?.aviso||'');setCancelada(!!actual?.cancelada);setMsg('')}
  async function guardar(e){e.preventDefault();if(!editor)return;const {dia,bloque,modo}=editor;const fecha=fechaSemana(lunes,dia-1);
    if(!cancelada&&profesor.trim()&&materia.trim()){
      const otro=grupo==='6'?'7-8':'6';const otraExcepcion=cambioMap[key(otro,dia,bloque)];const otra=otraExcepcion||baseMap[key(otro,dia,bloque)];
      if(otra&&!otra.cancelada&&otra.profesor?.trim().toLowerCase()===profesor.trim().toLowerCase()){setMsg(`⚠️ ${profesor} ya tiene clase con ${otro==='6'?'6.º':'7.º y 8.º'} en este bloque. Ajusta primero uno de los horarios.`);return}
    }
    const tabla=modo==='base'?'horario_base':'horario_cambios';const datos={grupo,dia,bloque,materia:materia.trim(),profesor:profesor.trim(),updated_at:new Date().toISOString()};if(modo==='cambio'){delete datos.dia;datos.fecha=fecha;datos.aviso=aviso.trim();datos.cancelada=cancelada}
    const {error}=await supabase.from(tabla).upsert(datos,{onConflict:modo==='base'?'grupo,dia,bloque':'fecha,grupo,bloque'});if(error){setMsg(error.message);return}setEditor(null);await cargar();setMsg('✅ Horario guardado y visible para estudiantes y profesores.')}
  async function quitarCambio(){const {dia,bloque}=editor;const {error}=await supabase.from('horario_cambios').delete().eq('fecha',fechaSemana(lunes,dia-1)).eq('grupo',grupo).eq('bloque',bloque);if(error){setMsg(error.message);return}setEditor(null);await cargar();setMsg('Cambio retirado: vuelve a aparecer el horario habitual.')}
  if(!editable){
    const fecha=fechaSemana(lunes,diaSeleccionado-1),esHoy=fecha===hoyBogota();
    const delDia=horas.map((hora,i)=>{const bloque=i+1,cambio=cambioMap[key(grupo,diaSeleccionado,bloque)],clase=cambio||baseMap[key(grupo,diaSeleccionado,bloque)];return {bloque,hora,cambio,clase}}).filter(x=>x.cambio||x.clase?.materia);
    const novedades=delDia.filter(x=>x.cambio);
    const actualizado=[...base.filter(x=>x.grupo===grupo),...cambios.filter(x=>x.grupo===grupo)].map(x=>x.updated_at).filter(Boolean).sort().at(-1);
    function volverHoy(){setLunes(semanaInicial());setDiaSeleccionado(diaInicial())}
    return <section className="studentSchedule"><div className="studentScheduleHeading"><span>MI HORARIO · {grupo==='6'?'6.º':'7.º Y 8.º'}</span><h2>{esHoy?'Clases de hoy':`${dias[diaSeleccionado-1]} ${fecha}`}</h2><p>{esHoy?`Hoy, ${fecha}`:`Semana del ${lunes} al ${fechaSemana(lunes,4)}`}</p></div>
      <div className="studentWeekControls"><button type="button" onClick={()=>setLunes(fechaSemana(lunes,-7))}>← Semana anterior</button><button type="button" onClick={volverHoy}>Volver a hoy</button><button type="button" onClick={()=>setLunes(fechaSemana(lunes,7))}>Semana siguiente →</button></div>
      <div className="studentDayTabs" role="group" aria-label="Elegir día de clases">{dias.map((nombre,i)=><button type="button" key={nombre} aria-pressed={diaSeleccionado===i+1} className={diaSeleccionado===i+1?'selected':''} onClick={()=>setDiaSeleccionado(i+1)}><b>{nombre.slice(0,3)}</b><small>{fechaSemana(lunes,i).slice(8)}</small></button>)}</div>
      {msg&&<p className="notice" role="status">{msg}</p>}{cargando?<div className="placeholder">Cargando horario…</div>:<>
        {novedades.length>0&&<div className="studentScheduleAlert" role="status"><b>🔔 Cambios para {esHoy?'hoy':dias[diaSeleccionado-1].toLowerCase()}</b>{novedades.map(x=><p key={x.bloque}>{x.bloque}.ª hora: {x.cambio.cancelada?'clase cancelada':x.cambio.materia||'Sin clase asignada'}{!x.cambio.cancelada&&x.cambio.profesor&&` con ${x.cambio.profesor}`}{x.cambio.aviso&&` · ${x.cambio.aviso}`}</p>)}</div>}
        <div className="studentLessonList">{delDia.map(x=><React.Fragment key={x.bloque}>{x.bloque===4&&<div className="studentBreak">☀️ Descanso pedagógico · 9:45–10:15</div>}<article className={`studentLesson ${x.cambio?.cancelada?'studentLessonCancelled':x.cambio?'studentLessonChanged':''}`}><div className="studentLessonTime"><b>{x.bloque}.ª hora</b><small>{x.hora}</small></div><div><b>{x.cambio?.cancelada?'Clase cancelada':x.clase?.materia||'Sin clase asignada'}</b>{!x.cambio?.cancelada&&x.clase?.profesor&&<span>Profe {x.clase.profesor}</span>}{x.cambio&&<small>{x.cambio.cancelada?'🚫 Cancelada':'🔔 Cambio'}{x.cambio.aviso&&` · ${x.cambio.aviso}`}</small>}</div></article></React.Fragment>)}</div>
        {actualizado&&<p className="studentScheduleUpdated">Horario actualizado: {new Intl.DateTimeFormat('es-CO',{timeZone:'America/Bogota',day:'numeric',month:'long',hour:'numeric',minute:'2-digit'}).format(new Date(actualizado))}</p>}
      </>}</section>;
  }
  const fechaElegida=fechaSemana(lunes,diaSeleccionado-1);
  const docenteFiltrado=clasesProfesor.filter(x=>vistaDocente==='semana'||x.dia===diaSeleccionado);
  const renderBloque=(dia,bloque,g)=>{const b=baseMap[key(g,dia,bloque)],c=cambioMap[key(g,dia,bloque)],dato=c||b;
    return <article className={`teacherSlot ${c?.cancelada?'teacherSlotCancelled':c?'teacherSlotChanged':''}`} key={`${g}-${dia}-${bloque}`}><div className="teacherSlotTime"><b>{bloque}.ª hora</b><small>{horas[bloque-1]}</small></div><div className="teacherSlotSubject"><b>{c?.cancelada?'Clase cancelada':dato?.materia||'Sin clase asignada'}</b><span>{g==='6'?'Grado 6.º':'Grados 7.º y 8.º'}{!c?.cancelada&&dato?.profesor?` · Profe ${dato.profesor}`:''}</span>{c&&<small>🔔 {c.aviso||'Cambio para esta fecha'}</small>}</div><div className="teacherSlotActions"><button type="button" onClick={()=>abrir(dia,bloque,'cambio',g)}>Cambiar este día</button><button type="button" onClick={()=>abrir(dia,bloque,'base',g)}>Editar habitual</button></div></article>};
  const renderDia=dia=><article className="teacherDay" key={dia}><h3>{dias[dia-1]} <small>{fechaSemana(lunes,dia-1)}</small></h3>{Array.from({length:6},(_,i)=>i+1).map(bloque=><React.Fragment key={bloque}>{bloque===4&&<div className="studentBreak">☀️ Descanso · 9:45–10:15</div>}{renderBloque(dia,bloque,grupo)}</React.Fragment>)}</article>;
  return <section className="teacherSchedule"><div className="teacherScheduleHeader"><span>ORGANIZACIÓN ESCOLAR</span><h2>🕒 Horario docente</h2><p>Consulta clases y publica novedades por fecha cuando cambie la jornada.</p></div>
    <div className="teacherScheduleToolbar"><label>Grupo<select value={grupo} onChange={e=>{setGrupo(e.target.value);setEditor(null)}}><option value="6">6.º</option><option value="7-8">7.º y 8.º</option></select></label><label>Profesor<select value={filtroProfesor} onChange={e=>{setFiltroProfesor(e.target.value);setEditor(null)}}><option value="">Todos</option>{profesores.map(nombre=><option value={nombre} key={nombre}>{nombre}</option>)}</select></label><div className="teacherViewSwitch" role="group" aria-label="Modo de consulta"><button type="button" aria-pressed={vistaDocente==='dia'} className={vistaDocente==='dia'?'selected':''} onClick={()=>setVistaDocente('dia')}>Día</button><button type="button" aria-pressed={vistaDocente==='semana'} className={vistaDocente==='semana'?'selected':''} onClick={()=>setVistaDocente('semana')}>Semana</button></div></div>
    <div className="studentWeekControls"><button type="button" onClick={()=>{setLunes(fechaSemana(lunes,-7));setEditor(null)}}>← Semana anterior</button><strong>{lunes} a {fechaSemana(lunes,4)}</strong><button type="button" onClick={()=>{setLunes(semanaInicial());setDiaSeleccionado(diaInicial());setEditor(null)}}>Volver a hoy</button><button type="button" onClick={()=>{setLunes(fechaSemana(lunes,7));setEditor(null)}}>Semana siguiente →</button></div>
    {vistaDocente==='dia'&&<div className="studentDayTabs" role="group" aria-label="Día del horario">{dias.map((nombre,i)=><button type="button" key={nombre} aria-pressed={diaSeleccionado===i+1} className={diaSeleccionado===i+1?'selected':''} onClick={()=>{setDiaSeleccionado(i+1);setEditor(null)}}><b>{nombre.slice(0,3)}</b><small>{fechaSemana(lunes,i).slice(8)}</small></button>)}</div>}
    {msg&&<p className="notice" role="status">{msg}</p>}
    {cargando?<div className="placeholder">Cargando horario…</div>:filtroProfesor?<div className="teacherFiltered"><h3>{filtroProfesor} · {vistaDocente==='dia'?`${dias[diaSeleccionado-1]} ${fechaElegida}`:`semana del ${lunes}`}</h3>{docenteFiltrado.length?docenteFiltrado.map(x=><article className={`teacherSlot ${x.cambio?'teacherSlotChanged':''}`} key={`${x.fecha}-${x.grupo}-${x.bloque}`}><div className="teacherSlotTime"><b>{vistaDocente==='semana'?dias[x.dia-1]:`${x.bloque}.ª hora`}</b><small>{x.fecha} · {horas[x.bloque-1]}</small></div><div className="teacherSlotSubject"><b>{x.materia}</b><span>{x.grupo==='6'?'Grado 6.º':'Grados 7.º y 8.º'} · {x.bloque}.ª hora</span>{x.cambio&&<small>🔔 {x.aviso||'Cambio para esta fecha'}</small>}</div><div className="teacherSlotActions"><button type="button" onClick={()=>abrir(x.dia,x.bloque,'cambio',x.grupo)}>Cambiar este día</button><button type="button" onClick={()=>abrir(x.dia,x.bloque,'base',x.grupo)}>Editar habitual</button></div></article>):<div className="placeholder">No hay clases asignadas a este profesor en {vistaDocente==='dia'?'este día':'esta semana'}.</div>}</div>:vistaDocente==='dia'?renderDia(diaSeleccionado):<div className="teacherWeekGrid">{dias.map((_,i)=>renderDia(i+1))}</div>}
    {editor&&<form id="schedule-edit-form" className="card scheduleEditor" onSubmit={guardar}><h3>{editor.modo==='base'?'Editar horario habitual':'Cambio solo para esta fecha'} · {grupo==='6'?'6.º':'7.º y 8.º'} · {dias[editor.dia-1]} {fechaSemana(lunes,editor.dia-1)} · {editor.bloque}.ª hora</h3><label>Materia<select value={materia} onChange={e=>{setMateria(e.target.value);setProfesor(docente(e.target.value))}}>{materias.map(x=><option key={x} value={x}>{x||'Sin clase asignada'}</option>)}</select></label><label>Profesor<input value={profesor} onChange={e=>setProfesor(e.target.value)} placeholder="Nombre del profesor o reemplazo"/></label>{editor.modo==='cambio'&&<><label>Motivo o aviso<input value={aviso} onChange={e=>setAviso(e.target.value)} placeholder="Ej. profesor ausente; trabajo autónomo"/></label><label><input type="checkbox" checked={cancelada} onChange={e=>setCancelada(e.target.checked)}/> Clase cancelada</label></>}<div className="scheduleActions"><button className="save" type="submit">Guardar y publicar</button>{editor.modo==='cambio'&&cambioMap[key(grupo,editor.dia,editor.bloque)]&&<button type="button" onClick={quitarCambio}>Quitar cambio</button>}<button type="button" onClick={()=>setEditor(null)}>Cerrar</button></div></form>}
    <p className="taskHelp">Descanso pedagógico: 9:45–10:15. Las horas 5.ª y 6.ª están disponibles para nuevas clases.</p>
  </section>;
}
