import React,{useState} from 'react';
import readExcelFile from 'read-excel-file/browser';
import {supabase} from './lib/supabase';

import {interpretarHojas,claveNombre} from './importarExcel';

const correoValido=s=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);
export function ImportarEstudiantes({existentes,alTerminar}){const[filas,setFilas]=useState([]),[omitidas,setOmitidas]=useState([]),[archivo,setArchivo]=useState(''),[leyendo,setLeyendo]=useState(false),[guardando,setGuardando]=useState(false),[msg,setMsg]=useState('');
  async function leer(e){const file=e.target.files?.[0];setFilas([]);setOmitidas([]);setMsg('');if(!file)return;setArchivo(file.name);setLeyendo(true);try{const hojas=await readExcelFile(file);const resultado=interpretarHojas(hojas);const actualesPorCorreo=new Map(existentes.filter(x=>x.email).map(x=>[x.email.toLowerCase(),x]));const actualesPorNombre=new Map();for(const x of existentes){const k=`${x.grado}:${claveNombre(x.nombre)}`;if(!actualesPorNombre.has(k))actualesPorNombre.set(k,[]);actualesPorNombre.get(k).push(x)}setFilas(resultado.filas.map(f=>{const matched=actualesPorCorreo.get(f.email)||(actualesPorNombre.get(`${f.grado}:${claveNombre(f.nombre)}`)||[])[0];return{...f,id:matched?.id||'',omitir:!!matched}}));setOmitidas(resultado.omitidas)}catch(err){setMsg(`No se pudo leer el Excel: ${err.message}`)}setLeyendo(false)}
  function cambiar(clave,campo,valor){setFilas(v=>v.map(f=>f.clave===clave?{...f,[campo]:valor}:f))}
  const activos=filas.filter(f=>!f.omitir), emails=new Set(), nombres=new Set();const errores=[];for(const f of activos){if(!f.nombre)errores.push(`${f.hoja}, fila ${f.fila}: falta el nombre`);if(!correoValido(f.email))errores.push(`${f.hoja}, fila ${f.fila}: correo inválido`);if(!Number.isInteger(f.grado)||f.grado<1||f.grado>8)errores.push(`${f.hoja}, fila ${f.fila}: grado inválido (1–8)`);if(emails.has(f.email))errores.push(`${f.hoja}, fila ${f.fila}: correo repetido en el archivo`);emails.add(f.email);const key=`${f.grado}:${claveNombre(f.nombre)}`;if(nombres.has(key))errores.push(`${f.hoja}, fila ${f.fila}: nombre repetido en el grado`);nombres.add(key);const otro=existentes.find(x=>x.email?.toLowerCase()===f.email&&x.id!==f.id);if(otro)errores.push(`${f.hoja}, fila ${f.fila}: correo ya asignado a ${otro.nombre}`);if(!f.id&&existentes.some(x=>x.grado===f.grado&&claveNombre(x.nombre)===claveNombre(f.nombre)))errores.push(`${f.hoja}, fila ${f.fila}: estudiante existente; vincúlalo o omite la fila`)}if(new Set(activos.map(f=>f.id).filter(Boolean)).size!==activos.filter(f=>f.id).length)errores.push('Dos filas intentan actualizar al mismo estudiante.');
  async function importar(){if(guardando||errores.length||!activos.length)return;setGuardando(true);setMsg('');const{data,error}=await supabase.rpc('importar_estudiantes',{filas:activos.map(({nombre,email,grado,id})=>({nombre,email,grado,id:id||null}))});if(error)setMsg('No se realizó la importación: '+error.message);else{setMsg(`Importación completa: ${data.creados} creados y ${data.actualizados} actualizados.`);setFilas([]);await alTerminar()}setGuardando(false)}
  return <div className="bulkImport"><h3>📥 Carga masiva desde Excel</h3><p>Prepara un archivo <b>.xlsx</b> con tres columnas tituladas <b>Nombre del estudiante</b>, <b>Correo</b> y <b>Grado</b> (número del 1 al 8). Puede tener varias hojas: se leerán todas las que contengan esas tres columnas. El grado se toma de cada fila, no del nombre de la hoja.</p><p>Ejemplo: <b>YEREMY JOSUE ALVAREZ PEREIRA</b> · <b>yeremyalvarezp@claudinamunera.edu.co</b> · <b>1</b>. Los correos deben existir o estar preparados para el acceso de sus estudiantes. Revisa la vista previa: esta acción no crea cuentas de Google ni buzones de correo.</p><label>Seleccionar Excel<input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={leer}/></label>{leyendo&&<p>Leyendo hojas…</p>}{archivo&&<p><b>{archivo}</b>: {filas.length} filas detectadas; {activos.length} seleccionadas para importar.</p>}{omitidas.map((o,i)=><p className="importWarning" key={i}>{o}</p>)}{filas.length>0&&<><p>Las coincidencias existentes aparecen marcadas para omitir. Si necesitas completarles el correo o actualizar el grado, desmarca «Omitir» y selecciona su ficha. Corrige cualquier dato antes de confirmar.</p><div className="importTableWrap"><table className="importTable"><thead><tr><th>Hoja/fila</th><th>Nombre del estudiante</th><th>Correo</th><th>Grado</th><th>Ficha existente</th><th>Omitir</th></tr></thead><tbody>{filas.map(f=><tr key={f.clave}><td>{f.hoja} · {f.fila}</td><td><input aria-label={`Nombre fila ${f.fila}`} value={f.nombre} onChange={e=>cambiar(f.clave,'nombre',e.target.value)}/></td><td><input type="email" aria-label={`Correo fila ${f.fila}`} value={f.email} onChange={e=>cambiar(f.clave,'email',e.target.value.toLowerCase())}/></td><td><select aria-label={`Grado fila ${f.fila}`} value={f.grado||''} onChange={e=>cambiar(f.clave,'grado',Number(e.target.value))}><option value="">—</option>{Array.from({length:8},(_,i)=><option key={i} value={i+1}>{i+1}°</option>)}</select></td><td><select aria-label={`Ficha existente fila ${f.fila}`} value={f.id} onChange={e=>cambiar(f.clave,'id',e.target.value)}><option value="">Crear nuevo</option>{existentes.map(x=><option key={x.id} value={x.id}>{x.grado}° · {x.nombre}</option>)}</select></td><td><input type="checkbox" checked={f.omitir} onChange={e=>cambiar(f.clave,'omitir',e.target.checked)}/></td></tr>)}</tbody></table></div>{errores.slice(0,12).map((e,i)=><p className="importWarning" key={i}>{e}</p>)}{errores.length>12&&<p className="importWarning">Hay {errores.length-12} errores adicionales.</p>}<button className="save" disabled={guardando||errores.length>0||activos.length===0} onClick={importar}>{guardando?'Importando…':`Confirmar ${activos.length} estudiantes`}</button></>}{msg&&<p role="status" className="notice">{msg}</p>}</div>
}
