import React,{useEffect,useState} from 'react';
import {supabase} from './lib/supabase';
import {fechaBogota} from './ultimaActividad';
import escudo from './assets/escudo-claudina.png';
import './Invitados.css';

export function diasConvivencia(s,hoy=fechaBogota()){
 if(!s?.inicio||!s.verificado_hasta)return null;
 const desde=s.ultimo_incidente&&s.ultimo_incidente>s.inicio?s.ultimo_incidente:s.inicio;
 const hasta=s.verificado_hasta<hoy?s.verificado_hasta:hoy;
 if(desde>hasta)return null;
 return Math.floor((Date.parse(hasta+'T00:00:00Z')-Date.parse(desde+'T00:00:00Z'))/86400000);
}
export function PortalInvitados({salir}){
 const[datos,setDatos]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function cargar(){setLoading(true);setError('');const{data,error}=await supabase.rpc('portal_invitados');if(error)setError('Los avisos y el seguimiento de convivencia todavía no están disponibles.');else setDatos(data);setLoading(false)}
 useEffect(()=>{cargar()},[]);
 const dias=diasConvivencia(datos?.seguimiento);
 return <main className="guestPortal"><header><img className="brandShield" src={escudo} alt="Escudo Claudina Múnera"/><div><h1>Claudina App</h1><p>Familias y comunidad · Acceso de invitados</p></div><button type="button" onClick={salir}>Ingresar a mi cuenta</button></header>
 <section><div className="hero"><span>BIENVENIDOS A NUESTRA COMUNIDAD</span><h2>Convivimos, cuidamos y transformamos</h2><p>Una comunidad que aprende a cuidar sus espacios y a resolver sus diferencias con diálogo.</p></div>
 <article className="card"><h2>Nuestra institución</h2><p>Centro Educativo Rural Claudina Múnera · Vereda La Corrala, Caldas, Antioquia.</p><p>“Acogemos con amor, sabiduría y liderazgo transformando realidades”.</p><p>Claudina App acompaña los turnos de aseo, la participación estudiantil, los horarios y los avisos de nuestra comunidad educativa.</p><a href="https://www.claudinamunera.edu.co/" target="_blank" rel="noreferrer">Conoce la página institucional ↗</a></article>
 <article className="card guestCounter"><span>🌱 DÍAS CONSECUTIVOS SIN INCIDENTES CONFIRMADOS</span><strong>{loading?'…':dias==null?'Por iniciar':dias}</strong><p>{dias==null?'El equipo docente confirmará la fecha de inicio y el seguimiento.':'Seguimos construyendo una convivencia respetuosa.'}</p>{datos?.seguimiento?.verificado_hasta&&<small>Actualizado al {datos.seguimiento.verificado_hasta} · Días calendario hasta la última revisión docente.</small>}</article>
 {loading?<p role="status">Cargando publicaciones…</p>:error?<div className="notice" role="status">{error}<button type="button" onClick={cargar}>Reintentar</button></div>:<>
 <article className="card"><h2>📣 Avisos para la comunidad</h2>{datos?.avisos?.length?datos.avisos.map((a,i)=><div className="guestEntry" key={i}><h3>{a.titulo}</h3><p>{a.contenido}</p>{a.fecha_evento&&<small>Fecha: {a.fecha_evento}</small>}</div>):<p>Pronto compartiremos nuevos avisos públicos.</p>}</article>
 <article className="card"><h2>🤝 Así resolvemos nuestros conflictos</h2><p>Experiencias de diálogo, acuerdos y aprendizaje compartidas por el equipo docente.</p>{datos?.casos?.length?datos.casos.map((c,i)=><div className="guestEntry" key={i}><small>{c.fecha}</small><h3>{c.titulo}</h3><h4>¿Qué ocurrió?</h4><p>{c.situacion}</p><h4>¿Cómo lo solucionamos?</h4><p>{c.solucion}</p><h4>Nuestros acuerdos</h4><p>{c.acuerdos}</p><h4>¿Qué aprendimos?</h4><p>{c.aprendizaje}</p></div>):<p>Aún no hay experiencias publicadas.</p>}</article></>}
 </section><footer>Claudina App · C.E.R. Claudina Múnera <span className="designCredit">Designed by Ghost</span></footer></main>;
}
const nuevo=()=>({fecha:fechaBogota(),titulo:'',situacion:'',solucion:'',acuerdos:'',aprendizaje:'',confirmado:true,publicado:false});
export function ConvivenciaProfesor(){
 const[lista,setLista]=useState([]),[seguimiento,setSeguimiento]=useState({inicio:'',verificado_hasta:''}),[form,setForm]=useState(nuevo),[id,setId]=useState(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[listo,setListo]=useState(false);
 async function cargar(){const[{data:c,error:e},{data:s,error:es}]=await Promise.all([supabase.from('convivencia_publicaciones').select('*').order('fecha',{ascending:false}),supabase.from('convivencia_seguimiento').select('inicio,verificado_hasta').eq('id',1).single()]);setListo(!e&&!es);if(e||es){setMsg('Falta habilitar el módulo de convivencia en Supabase.');return}setLista(c||[]);setSeguimiento({inicio:s.inicio||'',verificado_hasta:s.verificado_hasta||''})}
 useEffect(()=>{cargar()},[]);
 const campo=(n,v)=>setForm(f=>({...f,[n]:v}));
 async function guardarSeguimiento(e){e.preventDefault();setBusy(true);const{error}=await supabase.from('convivencia_seguimiento').update({inicio:seguimiento.inicio||null,verificado_hasta:seguimiento.verificado_hasta||null}).eq('id',1);setMsg(error?error.message:'✅ Seguimiento actualizado.');setBusy(false)}
 async function guardarCaso(e){e.preventDefault();if(busy)return;if(form.publicado&&(!form.solucion.trim()||!form.acuerdos.trim()||!form.aprendizaje.trim())){setMsg('Completa solución, acuerdos y aprendizaje antes de publicar.');return}setBusy(true);const payload={...form,titulo:form.titulo.trim(),situacion:form.situacion.trim()};const{error}=id?await supabase.from('convivencia_publicaciones').update(payload).eq('id',id):await supabase.from('convivencia_publicaciones').insert(payload);if(error)setMsg(error.message);else{setMsg(form.publicado?'✅ Experiencia publicada para invitados.':'✅ Borrador guardado.');setId(null);setForm(nuevo());await cargar()}setBusy(false)}
 async function ocultar(c){setBusy(true);const{error}=await supabase.from('convivencia_publicaciones').update({publicado:false}).eq('id',c.id);if(error)setMsg(error.message);else{setMsg('Publicación ocultada. El incidente sigue contando en el seguimiento.');await cargar()}setBusy(false)}
 return <section><h2>🤝 Convivencia y comunidad</h2><p>Registra situaciones confirmadas y comparte aprendizajes sin nombres, cursos específicos ni detalles que identifiquen personas. Solo los profesores administran estas publicaciones.</p>{msg&&<p className="notice" role="status">{msg}</p>}{!listo?<button type="button" onClick={cargar}>Volver a comprobar</button>:<>
 <form className="card avisoForm" onSubmit={guardarSeguimiento}><h3>🌱 Seguimiento de convivencia</h3><label>Inicio del seguimiento<input type="date" required max={fechaBogota()} value={seguimiento.inicio} onChange={e=>setSeguimiento(s=>({...s,inicio:e.target.value}))}/></label><label>Revisión confirmada hasta<input type="date" required min={seguimiento.inicio||undefined} max={fechaBogota()} value={seguimiento.verificado_hasta} onChange={e=>setSeguimiento(s=>({...s,verificado_hasta:e.target.value}))}/></label><small>Confirma esta fecha después de revisar lo ocurrido. Los incidentes confirmados reinician la racha, incluso si su publicación es privada.</small><button className="save" disabled={busy}>Guardar seguimiento</button></form>
 <form className="card avisoForm" onSubmit={guardarCaso}><h3>{id?'Editar experiencia':'Registrar un conflicto y su solución'}</h3><label>Fecha del incidente<input type="date" max={fechaBogota()} required value={form.fecha} onChange={e=>campo('fecha',e.target.value)}/></label><label>Título<input required maxLength={120} value={form.titulo} onChange={e=>campo('titulo',e.target.value)}/></label>{[['situacion','¿Qué ocurrió?'],['solucion','¿Cómo se solucionó?'],['acuerdos','Acuerdos alcanzados'],['aprendizaje','¿Qué aprendimos?']].map(([k,label])=><label key={k}>{label}<textarea required={k==='situacion'||form.publicado} maxLength={2000} value={form[k]} onChange={e=>campo(k,e.target.value)}/></label>)}<label><input type="checkbox" checked={form.confirmado} onChange={e=>campo('confirmado',e.target.checked)}/> Incidente confirmado: reinicia el contador</label><label><input type="checkbox" checked={form.publicado} onChange={e=>campo('publicado',e.target.checked)}/> Aprobar publicación para invitados: revisé que no identifica a ninguna persona</label><button className="save" disabled={busy}>{busy?'Guardando…':form.publicado?'Guardar y publicar':'Guardar borrador'}</button>{id&&<button type="button" disabled={busy} onClick={()=>{setId(null);setForm(nuevo())}}>Cancelar edición</button>}</form>
 <h3>Experiencias registradas</h3>{lista.length?lista.map(c=><article className="card" key={c.id}><small>{c.fecha} · {c.publicado?'Público':'Borrador'} · {c.confirmado?'Incidente confirmado':'Sin confirmar'}</small><h3>{c.titulo}</h3><p>{c.situacion}</p><p>{c.solucion}</p><button disabled={busy} onClick={()=>{setId(c.id);setForm(Object.fromEntries(Object.keys(nuevo()).map(k=>[k,c[k]])))}}>Editar</button>{c.publicado&&<button disabled={busy} onClick={()=>ocultar(c)}>Ocultar publicación</button>}</article>):<p>Todavía no hay conflictos registrados.</p>}</>}
 </section>;
}
