import SelectorFotos from './SelectorFotos';
import FotoTarea from './FotoTarea';
import {leerBorrador,guardarBorrador,leerFotosBorrador,guardarFotosBorrador,borrarBorrador} from './borradorAseo';
import {materiasEscolares} from './materias';
import React,{useState,useEffect} from 'react';
import {supabase} from './lib/supabase';
import {fechaBogota} from './ultimaActividad';
export function TareasEstudiante({ficha}){
 const clave=`claudina-clean:tarea:${ficha.id}`,borrador=leerBorrador(clave)||{};
 const[fotos,setFotos]=useState([]);
 const[materia,setMateria]=useState(borrador.materia||''),[titulo,setTitulo]=useState(borrador.titulo||''),[contenido,setContenido]=useState(borrador.contenido||''),[fecha,setFecha]=useState(borrador.fecha||''),[propuestas,setPropuestas]=useState([]),[tareas,setTareas]=useState([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 async function cargar(){const[{data:p,error:ep},{data:t,error:et}]=await Promise.all([supabase.rpc('tareas_propuestas_listar'),supabase.from('avisos').select('id,titulo,contenido,grado,fecha_evento,foto_path').eq('publicado',true).eq('tipo','tarea').order('fecha_evento',{ascending:true})]);if(ep||et)setMsg('No se pudieron cargar las tareas: '+(ep||et).message);else{setPropuestas(p||[]);setTareas(t||[])}}
 useEffect(()=>{cargar();leerFotosBorrador(clave).then(setFotos)},[]);
 useEffect(()=>{guardarBorrador(clave,{materia,titulo,contenido,fecha})},[materia,titulo,contenido,fecha]);
 function seleccionarFotos(archivos){setFotos(archivos);guardarFotosBorrador(clave,archivos).catch(()=>setMsg('No se pudo conservar la foto para una recarga.'))}
 async function enviar(e){e.preventDefault();if(busy)return;setBusy(true);setMsg('');let foto=null;try{;if(fotos[0]){const f=fotos[0];if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>8388608)throw new Error('Selecciona una foto JPG, PNG o WebP de máximo 8 MB.');const{data:{user}}=await supabase.auth.getUser();foto=`${user.id}/${crypto.randomUUID()}.${f.type.split('/')[1]}`;const{error:subida}=await supabase.storage.from('tareas-fotos').upload(foto,f);if(subida)throw subida}const{error}=await supabase.rpc('tarea_proponer',{titulo:titulo.trim(),contenido:contenido.trim(),fecha,materia_asignada:materia,foto});if(error)throw error;setTitulo('');setContenido('');setFecha('');setMateria('');setFotos([]);await borrarBorrador(clave);await cargar();setMsg('✅ Tarea enviada al profesor para revisión.')}catch(e){if(foto)try{await supabase.storage.from('tareas-fotos').remove([foto])}catch{}setMsg('No se pudo enviar: '+e.message)}finally{setBusy(false)}}
 return <><article className="card"><h3>📝 Programar una tarea</h3><p>Ayuda a todos a recordar la tarea. El profesor la revisará y podrá editarla antes de publicarla.</p><form className="avisoForm" onSubmit={enviar}><label>Materia<select required value={materia} onChange={e=>setMateria(e.target.value)}><option value="">Selecciona la materia</option>{materiasEscolares.map(m=><option key={m} value={m}>{m}</option>)}</select></label><label>Título<input required maxLength={materia?117-materia.length:120} value={titulo} onChange={e=>setTitulo(e.target.value)}/></label><label>¿Qué hay que hacer?<textarea required maxLength={1000} value={contenido} onChange={e=>setContenido(e.target.value)}/></label><label>Fecha de entrega<input type="date" required min={fechaBogota()} value={fecha} onChange={e=>setFecha(e.target.value)}/></label><p>Foto de la tarea (opcional)</p><SelectorFotos archivos={fotos} onSeleccionar={seleccionarFotos} disabled={busy} onPreparar={()=>guardarBorrador(clave,{materia,titulo,contenido,fecha})}/><button className="save" disabled={busy||!materia||!titulo.trim()||!contenido.trim()||!fecha}>{busy?'Enviando…':'Enviar tarea'}</button></form>{msg&&<p role="status">{msg}</p>}{propuestas.length>0&&<details><summary>Mis propuestas de tareas ({propuestas.length})</summary>{propuestas.map(p=><p key={p.id}><b>{p.titulo}</b> · {p.estado==='pendiente'?'En revisión':p.estado==='publicada'?'Publicada':'No aprobada'}</p>)}</details>}</article><article className="card"><h3>📚 Tareas pendientes</h3>{tareas.length?tareas.map(t=><div className="avisoCard" key={t.id}><h4>{t.titulo}</h4><p>{t.contenido}</p><FotoTarea path={t.foto_path}/>{t.fecha_evento&&<b>Fecha de entrega: {t.fecha_evento}{t.fecha_evento<fechaBogota()?' · Fecha vencida':''}</b>}</div>):<p>No hay tareas publicadas para tu grado.</p>}</article></>;
}
function RevisionTarea({propuesta,alTerminar}){
 const[materia,setMateria]=useState(propuesta.materia||''),[titulo,setTitulo]=useState(propuesta.titulo),[contenido,setContenido]=useState(propuesta.contenido),[fecha,setFecha]=useState(propuesta.fecha_entrega),[grado,setGrado]=useState(propuesta.grado),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function revisar(publicar){if(busy)return;setBusy(true);setMsg('');try{const{error}=await supabase.rpc('tarea_revisar',{propuesta:propuesta.id,titulo:titulo.trim(),contenido:contenido.trim(),fecha,grado_destino:Number(grado),publicar,materia_asignada:materia||null});if(error)throw error;await alTerminar()}catch(e){setMsg('No se pudo revisar: '+e.message)}finally{setBusy(false)}}
 return <article className="card"><p><b>{propuesta.nombre}</b> · Grado {propuesta.grado}°</p><FotoTarea path={propuesta.foto_path}/><form className="avisoForm" onSubmit={e=>{e.preventDefault();revisar(true)}}><label>Materia<select required value={materia} onChange={e=>setMateria(e.target.value)}><option value="">Selecciona la materia</option>{materiasEscolares.map(m=><option key={m} value={m}>{m}</option>)}</select></label><label>Título<input required maxLength={materia?117-materia.length:120} value={titulo} onChange={e=>setTitulo(e.target.value)}/></label><label>Tarea<textarea required maxLength={1000} value={contenido} onChange={e=>setContenido(e.target.value)}/></label><label>Fecha de entrega<input type="date" required value={fecha} onChange={e=>setFecha(e.target.value)}/></label><label>Grado que verá la tarea<select value={grado} onChange={e=>setGrado(e.target.value)}>{Array.from({length:8},(_,i)=><option key={i+1} value={i+1}>{i+1}°</option>)}</select></label><button className="save" disabled={busy||!materia||!titulo.trim()||!contenido.trim()||!fecha}>Aprobar y publicar tarea</button><button type="button" disabled={busy} onClick={()=>revisar(false)}>No aprobar</button></form>{msg&&<p role="status" className="error">{msg}</p>}</article>;
}
export function TareasProfesor(){const[lista,setLista]=useState([]),[error,setError]=useState('');async function cargar(){const{data,error}=await supabase.rpc('tareas_propuestas_listar');if(error)setError('No se pudieron cargar las propuestas: '+error.message);else{setError('');setLista((data||[]).filter(p=>p.estado==='pendiente'))}}useEffect(()=>{cargar()},[]);return <section><h2>📝 Tareas propuestas por estudiantes</h2><p>Revisa el contenido, la fecha y el grado antes de publicar. Las tareas aprobadas aparecerán para estudiantes y acudientes.</p>{error?<p className="error">{error}</p>:lista.length?lista.map(p=><RevisionTarea key={p.id} propuesta={p} alTerminar={cargar}/>):<p>No hay tareas pendientes de revisión.</p>}</section>}
